### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by mkolmus** [vanheeringen-lab/gimmemotifs#102]
**To Reproduce**
```
conda create -n test1 python=3 gimmemotifs
conda activate test1 
gimme -h 
```

> Traceback (most recent call last):
>   File "/mbshome/mkolmus/anaconda3/envs/test1/bin/gimme", line 8, in <module>
>     from gimmemotifs.cli import cli
>   File "/mbshome/mkolmus/anaconda3/envs/test1/lib/python3.6/site-packages/gimmemotifs/cli.py", line 11, in <module>
>     from gimmemotifs import commands, __version__
>   File "/mbshome/mkolmus/anaconda3/envs/test1/lib/python3.6/site-packages/gimmemotifs/commands/__init__.py", line 15, in <module>
>     "{0}.{1}".format(__name__, cmdname), globals(), locals(), [cmdname], level
>   File "/mbshome/mkolmus/anaconda3/envs/test1/lib/python3.6/site-packages/gimmemotifs/commands/background.py", line 8, in <module>
>     from gimmemotifs.background import create_background_file
>   File "/mbshome/mkolmus/anaconda3/envs/test1/lib/python3.6/site-packages/gimmemotifs/background.py", line 36, in <module>
>     from gimmemotifs.utils import number_of_seqs_in_file, as_fasta
>   File "/mbshome/mkolmus/anaconda3/envs/test1/lib/python3.6/site-packages/gimmemotifs/utils.py", line 36, in <module>
>     from gimmemotifs.rocmetrics import ks_pvalue
>   File "/mbshome/mkolmus/anaconda3/envs/test1/lib/python3.6/site-packages/gimmemotifs/rocmetrics.py", line 14, in <module>
>     from sklearn.metrics import (
>   File "/mbshome/mkolmus/anaconda3/envs/test1/lib/python3.6/site-packages/sklearn/__init__.py", line 83, in <module>
>     from .utils._show_versions import show_versions
>   File "/mbshome/mkolmus/anaconda3/envs/test1/lib/python3.6/site-packages/sklearn/utils/_show_versions.py", line 12, in <module>
>     from ._openmp_helpers import _openmp_parallelism_enabled
> ImportError: dlopen: cannot load any more object with static TLS
> 

**Installation information (please complete the following information):**
 - OS:  Linux
 - Installation conda

> # packages in environment at /mbshome/mkolmus/anaconda3/envs/test1:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                 conda_forge    conda-forge
> _openmp_mutex             4.5                       0_gnu    conda-forge
> _py-xgboost-mutex         2.0                       cpu_0    conda-forge
> alsa-lib                  1.1.5             h516909a_1002    conda-forge
> appdirs                   1.4.3                      py_1    conda-forge
> arrow-cpp                 0.15.1           py36h982ac2c_6    conda-forge
> attrs                     19.3.0                     py_0    conda-forge
> backcall                  0.1.0                      py_0    conda-forge
> backports                 1.0                        py_2    conda-forge
> bedtools                  2.29.2               hc088bd4_0    bioconda
> biopython                 1.76             py36h516909a_0    conda-forge
> bleach                    3.1.0                      py_0    conda-forge
> boltons                   20.0.0                     py_0    conda-forge
> boost-cpp                 1.70.0               ha2d47e9_1    conda-forge
> brotli                    1.0.7             he1b5a44_1000    conda-forge
> bucketcache               0.12.1                   py36_1    conda-forge
> bzip2                     1.0.8                h516909a_2    conda-forge
> c-ares                    1.15.0            h516909a_1001    conda-forge
> ca-certificates           2019.11.28           hecc5488_0    conda-forge
> certifi                   2019.11.28               py36_0    conda-forge
> cffi                      1.13.2           py36h8022711_0    conda-forge
> chardet                   3.0.4                 py36_1003    conda-forge
> click                     7.0                        py_0    conda-forge
> configparser              3.7.3                    py36_1    conda-forge
> cryptography              2.8              py36h72c5cf5_1    conda-forge
> curl                      7.65.3               hf8cf82a_0    conda-forge
> cycler                    0.10.0                     py_2    conda-forge
> dbus                      1.13.6               he372182_0    conda-forge
> decorator                 4.4.1                      py_0    conda-forge
> defusedxml                0.6.0                      py_0    conda-forge
> dinamo                    1.0                  h78a066a_0    bioconda
> diskcache                 4.0.0                      py_0    conda-forge
> double-conversion         3.1.5                he1b5a44_2    conda-forge
> entrypoints               0.3                   py36_1000    conda-forge
> expat                     2.2.5             he1b5a44_1004    conda-forge
> feather-format            0.4.0                   py_1003    conda-forge
> fontconfig                2.13.1            he4413a7_1000    conda-forge
> freetype                  2.10.0               he983fc9_1    conda-forge
> future                    0.18.2                   py36_0    conda-forge
> gadem                     1.3.1                h470a237_1    bioconda
> genomepy                  0.7.1                      py_0    bioconda
> gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
> gflags                    2.2.2             he1b5a44_1002    conda-forge
> ghostscript               9.22              hf484d3e_1001    conda-forge
> giflib                    5.2.1                h516909a_1    conda-forge
> gimmemotifs               0.14.1           py36h516909a_1    bioconda
> glib                      2.58.3          py36h6f030ca_1002    conda-forge
> glog                      0.4.0                he1b5a44_1    conda-forge
> grpc-cpp                  1.25.0               h213be95_2    conda-forge
> gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
> gstreamer                 1.14.5               h36ae1b5_0    conda-forge
> homer                     4.10            pl526hc9558a2_0    bioconda
> icu                       58.2              hf484d3e_1000    conda-forge
> idna                      2.8                   py36_1000    conda-forge
> importlib_metadata        1.4.0                    py36_0    conda-forge
> ipykernel                 5.1.3            py36h5ca1d4c_0    conda-forge
> ipython                   7.11.1           py36h5ca1d4c_0    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> ipywidgets                7.5.1                      py_0    conda-forge
> jedi                      0.15.2                   py36_0    conda-forge
> jinja2                    2.10.3                     py_0    conda-forge
> joblib                    0.14.1                     py_0    conda-forge
> jpeg                      9c                h14c3975_1001    conda-forge
> jsonschema                3.2.0                    py36_0    conda-forge
> jupyter_client            5.3.4                    py36_1    conda-forge
> jupyter_core              4.6.1                    py36_0    conda-forge
> kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
> krb5                      1.16.4               h2fd8d38_0    conda-forge
> lcms2                     2.9                  hbd6801e_1    conda-forge
> libblas                   3.8.0               14_openblas    conda-forge
> libcblas                  3.8.0               14_openblas    conda-forge
> libcurl                   7.65.3               hda55be3_0    conda-forge
> libdeflate                1.5                  h516909a_0    conda-forge
> libedit                   3.1.20170329      hf8c457e_1001    conda-forge
> libevent                  2.1.10               h72c5cf5_0    conda-forge
> libffi                    3.2.1             he1b5a44_1006    conda-forge
> libgcc                    7.2.0                h69d50b8_2    conda-forge
> libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
> libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
> libgomp                   9.2.0                h24d8f2e_2    conda-forge
> libiconv                  1.15              h516909a_1005    conda-forge
> liblapack                 3.8.0               14_openblas    conda-forge
> libopenblas               0.3.7                h5ec1e0e_6    conda-forge
> libpng                    1.6.37               hed695b0_0    conda-forge
> libprotobuf               3.11.0               h8b12597_0    conda-forge
> libsodium                 1.0.17               h516909a_0    conda-forge
> libssh2                   1.8.2                h22169c7_2    conda-forge
> libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
> libtiff                   4.1.0                hc3755c2_3    conda-forge
> libuuid                   2.32.1            h14c3975_1000    conda-forge
> libxcb                    1.13              h14c3975_1002    conda-forge
> libxgboost                0.90                 he1b5a44_4    conda-forge
> libxml2                   2.9.9                h13577e0_2    conda-forge
> libxslt                   1.1.32            hae48121_1003    conda-forge
> logbook                   1.5.3            py36h516909a_0    conda-forge
> logomaker                 0.8                        py_0    bioconda
> lz4-c                     1.8.3             he1b5a44_1001    conda-forge
> markupsafe                1.1.1            py36h516909a_0    conda-forge
> matplotlib                3.1.1                    py36_0    conda-forge
> matplotlib-base           3.1.1            py36hfd891ef_0    conda-forge
> meme                      5.0.5           py36pl526h19b89cf_0    bioconda
> mistune                   0.8.4           py36h516909a_1000    conda-forge
> more-itertools            8.1.0                      py_0    conda-forge
> mpi                       1.0                     openmpi    conda-forge
> mysql-connector-c         6.1.11            hc9bbbdd_1005    conda-forge
> nbconvert                 5.6.1                    py36_0    conda-forge
> nbformat                  5.0.3                      py_0    conda-forge
> ncurses                   6.1               hf484d3e_1002    conda-forge
> norns                     0.1.5                      py_0    bioconda
> nose                      1.3.7                 py36_1003    conda-forge
> notebook                  6.0.2                    py36_0    conda-forge
> numpy                     1.17.5           py36h95a1406_0    conda-forge
> olefile                   0.46                       py_0    conda-forge
> openjdk                   11.0.1            h600c080_1018    conda-forge
> openmpi                   4.0.2                hd49bf07_2    conda-forge
> openssl                   1.1.1d               h516909a_0    conda-forge
> pandas                    0.25.3           py36hb3f55d8_0    conda-forge
> pandoc                    2.9.1.1                       0    conda-forge
> pandocfilters             1.4.2                      py_1    conda-forge
> parquet-cpp               1.5.1                         2    conda-forge
> parso                     0.5.2                      py_0    conda-forge
> pathlib                   1.0.1                    py36_1    conda-forge
> patsy                     0.5.1                      py_0    conda-forge
> pcre                      8.43                 he1b5a44_0    conda-forge
> perl                      5.26.2            h516909a_1006    conda-forge
> perl-algorithm-cluster    1.58            pl526h14c3975_0    bioconda
> perl-app-cpanminus        1.7044                  pl526_1    bioconda
> perl-base                 2.23                    pl526_1    bioconda
> perl-carp                 1.38                    pl526_3    bioconda
> perl-cgi                  4.44            pl526h14c3975_1    bioconda
> perl-common-sense         3.74                    pl526_2    bioconda
> perl-constant             1.33                    pl526_1    bioconda
> perl-dbi                  1.642                   pl526_0    bioconda
> perl-encode               2.88                    pl526_1    bioconda
> perl-exporter             5.72                    pl526_1    bioconda
> perl-extutils-makemaker   7.36                    pl526_1    bioconda
> perl-file-path            2.16                    pl526_0    bioconda
> perl-file-temp            0.2304                  pl526_2    bioconda
> perl-file-which           1.23                    pl526_0    bioconda
> perl-html-parser          3.72            pl526h6bb024c_5    bioconda
> perl-html-tagset          3.20                    pl526_3    bioconda
> perl-html-template        2.97                    pl526_1    bioconda
> perl-html-tree            5.07                    pl526_1    bioconda
> perl-json                 4.02                    pl526_0    bioconda
> perl-json-xs              2.34            pl526h6bb024c_3    bioconda
> perl-log-log4perl         1.49                    pl526_0    bioconda
> perl-math-cdf             0.1             pl526h14c3975_5    bioconda
> perl-parent               0.236                   pl526_1    bioconda
> perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
> perl-types-serialiser     1.0                     pl526_2    bioconda
> perl-xml-namespacesupport 1.12                    pl526_0    bioconda
> perl-xml-parser           2.44_01         pl526ha1d75be_1002    conda-forge
> perl-xml-sax              1.02                    pl526_0    bioconda
> perl-xml-sax-base         1.09                    pl526_0    bioconda
> perl-xml-sax-expat        0.51                    pl526_3    bioconda
> perl-xml-simple           2.25                    pl526_1    bioconda
> perl-xsloader             0.24                    pl526_0    bioconda
> perl-yaml                 1.29                    pl526_0    bioconda
> pexpect                   4.7.0                    py36_0    conda-forge
> pickleshare               0.7.5                 py36_1000    conda-forge
> pillow                    7.0.0            py36hefe7db6_0    conda-forge
> pip                       19.3.1                   py36_0    conda-forge
> prometheus_client         0.7.1                      py_0    conda-forge
> prompt_toolkit            3.0.2                      py_0    conda-forge
> prosampler                1.0                  hc9558a2_0    bioconda
> psutil                    5.6.7            py36h516909a_0    conda-forge
> pthread-stubs             0.4               h14c3975_1001    conda-forge
> ptyprocess                0.6.0                   py_1001    conda-forge
> py-xgboost                0.90                     py36_4    conda-forge
> pyarrow                   0.15.1           py36h8b68381_1    conda-forge
> pybedtools                0.8.1            py36he513fc3_0    bioconda
> pycparser                 2.19                     py36_1    conda-forge
> pyfaidx                   0.5.8                      py_1    bioconda
> pygments                  2.5.2                      py_0    conda-forge
> pyopenssl                 19.1.0                   py36_0    conda-forge
> pyparsing                 2.4.6                      py_0    conda-forge
> pyqt                      5.9.2            py36hcca6a23_4    conda-forge
> pyrsistent                0.15.7           py36h516909a_0    conda-forge
> pysam                     0.15.4           py36hbcae180_0    bioconda
> pysocks                   1.7.1                    py36_0    conda-forge
> python                    3.6.7             h357f687_1006    conda-forge
> python-dateutil           2.8.1                      py_0    conda-forge
> python-xxhash             1.4.1            py36h516909a_0    conda-forge
> pytz                      2019.3                     py_0    conda-forge
> pyyaml                    5.1.2            py36h516909a_0    conda-forge
> pyzmq                     18.1.1           py36h1768529_0    conda-forge
> qt                        5.9.7                h52cfd70_2    conda-forge
> re2                       2020.01.01           he1b5a44_0    conda-forge
> readline                  8.0                  hf8c457e_0    conda-forge
> represent                 1.6.0            py36h516909a_0    conda-forge
> requests                  2.22.0                   py36_1    conda-forge
> scikit-learn              0.22.1           py36hcdab131_1    conda-forge
> scipy                     1.4.1            py36h921218d_0    conda-forge
> seaborn                   0.9.0                      py_2    conda-forge
> send2trash                1.5.0                      py_0    conda-forge
> setuptools                45.1.0                   py36_0    conda-forge
> sip                       4.19.8          py36hf484d3e_1000    conda-forge
> six                       1.14.0                   py36_0    conda-forge
> sklearn-contrib-lightning 0.5.0                    py36_0    conda-forge
> snappy                    1.1.7             he1b5a44_1003    conda-forge
> sqlite                    3.30.1               hcee41ef_0    conda-forge
> statsmodels               0.10.2           py36hc1659b7_0    conda-forge
> terminado                 0.8.3                    py36_0    conda-forge
> testpath                  0.4.4                      py_0    conda-forge
> thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
> tk                        8.6.10               hed695b0_0    conda-forge
> tornado                   6.0.3            py36h516909a_0    conda-forge
> tqdm                      4.41.1                     py_0    conda-forge
> traitlets                 4.3.3                    py36_0    conda-forge
> trawler                   2.0                           3    bioconda
> ucsc-bedtogenepred        377                  h35c10e6_0    bioconda
> ucsc-bigbedtobed          357                           1    bioconda
> ucsc-genepredtobed        377                  h35c10e6_2    bioconda
> ucsc-genepredtogtf        377                  h35c10e6_2    bioconda
> ucsc-gff3togenepred       357                           1    bioconda
> ucsc-gtftogenepred        377                  h35c10e6_2    bioconda
> uriparser                 0.9.3                he1b5a44_1    conda-forge
> urllib3                   1.25.7                   py36_0    conda-forge
> wcwidth                   0.1.8                      py_0    conda-forge
> webencodings              0.5.1                      py_1    conda-forge
> weeder                    2.0                  h6bb024c_3    bioconda
> wheel                     0.33.6                   py36_0    conda-forge
> widgetsnbextension        3.5.1                    py36_0    conda-forge
> xdg                       4.0.1                      py_1    conda-forge
> xgboost                   0.90             py36he1b5a44_4    conda-forge
> xmltodict                 0.12.0                     py_0    conda-forge
> xorg-fixesproto           5.0               h14c3975_1002    conda-forge
> xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
> xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
> xorg-libx11               1.6.9                h516909a_0    conda-forge
> xorg-libxau               1.0.9                h14c3975_0    conda-forge
> xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
> xorg-libxext              1.3.4                h516909a_0    conda-forge
> xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
> xorg-libxi                1.7.10               h516909a_0    conda-forge
> xorg-libxrender           0.9.10            h516909a_1002    conda-forge
> xorg-libxtst              1.2.3             h516909a_1002    conda-forge
> xorg-recordproto          1.14.2            h516909a_1002    conda-forge
> xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
> xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
> xorg-xproto               7.0.31            h14c3975_1007    conda-forge
> xxmotif                   1.6                  h2d50403_2    bioconda
> xz                        5.2.4             h14c3975_1001    conda-forge
> yaml                      0.1.7             h14c3975_1001    conda-forge
> zeromq                    4.3.2                he1b5a44_2    conda-forge
> zipp                      1.0.0                      py_0    conda-forge
> zlib                      1.2.11            h516909a_1006    conda-forge
> zstd                      1.4.4                h3b9ef0a_1    conda-forge

**Additional context**

**Comment by simonvh** [comment]
I think it is this issue:
[pytorch/pytorch#2575 (comment)](https://github.com/pytorch/pytorch/issues/2575#issuecomment-523667875)

The Ubuntu version on mbscourse is indeed Trusty, which is not supported anymore by Ubuntu. @Maarten-vd-Sande @mkolmus can you try if this command solves it:

`LD_PRELOAD=~/anaconda3/lib/libgomp.sov`

(replace `/anaconda3/` with your anaconda install directory)

**Comment by Maarten-vd-Sande** [comment]
This seems to fix it for me on mbscourse :tada:

**Comment by simonvh** [comment]
Great. I'll add it to the FAQ.
