### ISSUE TITLE
SQLite concurrency

### ISSUE THREAD

**Issue by jessakay** [vanheeringen-lab/gimmemotifs#106]
**Describe the bug**
Unable to simultaneously process several datasets on a HPC cluster

**To Reproduce**
Launching 10+ parallel instances of gimmemotifs (each with `-N 12`)

**Expected behavior**
Possible to use gimmemotifs on many datasets in parallel

**Error logs**
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/local/anaconda3/envs/gimme/lib/python3.7/site-packages/diskcache/core.py", line 705, in _transact
    sql('BEGIN IMMEDIATE')
sqlite3.OperationalError: database is locked
```

**Installation information (please complete the following information):**
 - OS: Linux
 - Installation: conda
 - Version: 0.14.2

**Additional context**
To my understanding there is an inherent limitation on concurrency given the current implementation, but I was curious if there are plans to mitigate this sort of problem. Or perhaps it'd be nice to note this in the documentation.

Thanks!

**Comment by simonvh** [comment]
You are completely correct, this should be part of the documentation. I wanted to add an entry to the FAQ, but haven't done so. I have been unable to fix this so far. This has to do with the library I use for caching, and I haven't found one that supports concurrent access to the cache.

There is a (hacky) workaround, see also #97 

First delete your current cache (`~/.cache/gimmemotifs/`), as it will be corrupted. Then, you can use the following snippet of code in your job submission script. This will set the `XDG_CACHE_HOME` variable, which will be picked up by GimmMotifs. It will also copy your current cache, to save some time on regenerating files, if they're already there.

```
NEW_CACHE=$TMPDIR/cache
mkdir -p $NEW_CACHE
if [ -z $XDG_CACHE_HOME ]; then
    XDG_CACHE_HOME=$HOME/.cache
fi
cp -r $XDG_CACHE_HOME/gimmemotifs $NEW_CACHE/
export XDG_CACHE_HOME=$NEW_CACHE
echo 'Using $XDG_CACHE_HOME for cache'
```
Hope this helps. Let me know. If it also works for you I'll add it to the FAQ.

**Comment by jessakay** [comment]
That seems to have worked fine, thanks for the tip!
