### ISSUE TITLE
gimme maelstrom error

### ISSUE THREAD

**Issue by ritamonteiro** [vanheeringen-lab/gimmemotifs#108]
I'm trying to run gimme maelstrom but it gets stuck here:

2020-02-13 10:25:29,036 - INFO - Starting maelstrom
2020-02-13 10:25:29,066 - INFO - motif scanning (counts)
2020-02-13 10:25:29,067 - INFO - reading table
2020-02-13 10:25:30,782 - INFO - setting threshold
2020-02-13 10:25:32,287 - INFO - creating count table

And there is no error message.

I was using python 3.7 and switched to 3.6 and it didn't solve the issue.

**Comment by simonvh** [comment]
What is your input? How many rows/regions, and what is the size of the regions?

**Comment by ritamonteiro** [comment]
the input looks like this 
loc	0h_INPUT	0h_A_OCT4	0h_E_OCT4	24h_INPUT	24h_A_OCT4	24h_E_OCT4	2h_INPUT	2h_A_OCT4	2h_E_OCT4	8h_INPUT	8h_A_OCT4	8h_E_OCT4
chr1:3343475-3343938	1	47	68	0	6	9	2	47	33	2	17	21
chr1:3344072-3344540	3	50	59	2	5	8	2	34	26	0	12	14
chr1:4150826-4151318	4	68	81	5	79	82	2	78	52	2	61	70

There are 3119 regions with variable sizes.

**Comment by simonvh** [comment]
Hmm, your input set looks fine. This is a tab-delimited file? Regions are all ~500 bp?


One thing I would recommend is the following:

https://gimmemotifs.readthedocs.io/en/master/tutorials.html#find-differential-motifs
> In case of sequencing data, such as ChIP-seq, ATAC-seq or DNaseI seq, we recommend to use 
> log-transformed read counts which are mean-centered per row. For optimal results, it is 
> recommended to normalize between experiments (columns), for instance by quantile normalization 
> or scaling.

**Comment by ritamonteiro** [comment]
The regions are all 400bp. I transformed the data as suggested and run the same command again and it is still stuck here:

`2020-02-14 12:06:01,956 - INFO - creating count table`

I also ran it in another computer and this time I got this error:

```
> gimme) root@f22173313156:/app# gimme maelstrom counts_Oct4_acEP_DOWN_peaks_normalized.tsv mm10 Oct4_acEP_DOWN_norm_maelstrom.out
> 2020-02-14 13:25:59,810 - INFO - Starting maelstrom
> 2020-02-14 13:25:59,960 - INFO - motif scanning (counts)
> 2020-02-14 13:25:59,960 - INFO - reading table
> 2020-02-14 13:26:01,450 - INFO - using 10000 sequences
> 2020-02-14 13:26:01,451 - INFO - Creating index for genomic GC frequencies.
> Killed
```

**Comment by ritamonteiro** [comment]
So,I used a new file, the same used in your tutorial. 

This time the analysis runs but I still get an error when generating the html report: 

```
  File "/Users/gqc269/opt/miniconda3/envs/gimme-2/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/Users/gqc269/opt/miniconda3/envs/gimme-2/lib/python3.6/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/Users/gqc269/opt/miniconda3/envs/gimme-2/lib/python3.6/site-packages/gimmemotifs/commands/maelstrom.py", line 37, in maelstrom
    gc=gc,
  File "/Users/gqc269/opt/miniconda3/envs/gimme-2/lib/python3.6/site-packages/gimmemotifs/maelstrom.py", line 426, in run_maelstrom
    maelstrom_html_report(outdir, os.path.join(outdir, "final.out.txt"), pfmfile)
  File "/Users/gqc269/opt/miniconda3/envs/gimme-2/lib/python3.6/site-packages/gimmemotifs/report.py", line 262, in maelstrom_html_report
    del df.index.name
AttributeError: can't delete attribute
```

**Comment by simonvh** [comment]
I'm sorry you're having such a hard time getting it to work. The errors are all new to me. The last one looks similar to #109. I will look into it. Would you be able to sent me your original input file (and the genome you are using)? In that case I can see if I can find what goes wrong.

**Comment by simonvh** [comment]
I have released a new version (0.14.3) that should fix `AttributeError: can't delete attribute`. Importantly, the `pandas` version should be <1.0 (the most recent conda package should automatically do this). Please try it and see if it works.

**Comment by wdpontius** [comment]
I was also getting errors trying to run gimme maelstrom until seeing this issue and remaking the conda environment specifying pandas=0.25.3. The default pandas version was 1.0 when running conda create -n gimme python=3 gimmemotifs. This might be worth changing in the installation section of the README. Thanks for creating such a great suite of tools!

**Comment by simonvh** [comment]
@wdpontius thanks for reporting this. Was this with the latest version (0.14.4) of GimmeMotifs? Or with 0.14.3. I will carefully check the next release, to hopefully solve this issue (pandas 1.0 should also be supported).

**Comment by wdpontius** [comment]
@simonvh this was with v0.14.3.
