### ISSUE TITLE
dockerFile

### ISSUE THREAD

**Issue by michy999** [vanheeringen-lab/gimmemotifs#109]
It would be great if you could create a version of Gimme Motifs in a docker.  Any plans?

**Comment by simonvh** [comment]
There should be a docker version available here: [https://quay.io/repository/biocontainers/gimmemotifs](https://quay.io/repository/biocontainers/gimmemotifs). I don't heavily use docker myself, so I haven't tested it. If you happen to try it out, if would be great if you let know how that goes.

**Comment by michy999** [comment]
Hello Simon,
Thank you for this.  I will definitely test this out with 24hrs I am actively looking for novel motifs.  I have installed gimmemotifs and the test run went fine apart from I got the below error, I am hoping this is at the end of the process, is it?

Also, where and in what sequences the motifs were found in.  I am about to run gimme location I hope this tells me and doesn’t just reproduce the graph.

Thank you for producing this tool I will let you know about the docker.

2020-02-18 05:45:05,257 - INFO - creating statistics report
Traceback (most recent call last):
  File "/home/m.simon/.conda/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/m.simon/.conda/envs/gimme/lib/python3.7/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/home/m.simon/.conda/envs/gimme/lib/python3.7/site-packages/gimmemotifs/commands/motifs.py", line 247, in motifs
    link_matches=False,
  File "/home/m.simon/.conda/envs/gimme/lib/python3.7/site-packages/gimmemotifs/report.py", line 355, in roc_html_report
    del df.index.name
AttributeError: can't delete attribute


Best,
Michelle

**Comment by simonvh** [comment]
This seems to a similar error as #108. I will look into it.

**Comment by simonvh** [comment]
I have released a new version (0.14.3) that should fix this. Importantly, the `pandas` version should be <1.0 (the most recent conda package and docker build should automatically do this). Please try it and see if it works.

**Comment by michy999** [comment]
Hi Simon,
Apologies for not getting to this sooner, will this new release also document where the motifs within each input sequence?

Best,
Michelle
