### ISSUE TITLE
genomepy install leads to "No such file or directory"

### ISSUE THREAD

**Issue by plachta11b** [vanheeringen-lab/gimmemotifs#115]
**Describe the bug**
genomepy fails to install genome in docker container. 

**To Reproduce**
`docker run -it quay.io/biocontainers/gimmemotifs:0.14.4--py37h516909a_0 genomepy install hg38 UCSC --annotation`

**Error logs**

> Downloading genome from http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz...
> gunzip: /root/.local/share/genomes/hg38/tmphz_jewej/hg38.fa: No such file or directory
> Traceback (most recent call last):

...

> subprocess.CalledProcessError: Command '['gunzip', '-f', '/root/.local/share/genomes/hg38/tmphz_jewej/hg38.fa']' returned non-zero exit status 1.

**Installation information (please complete the following information):**
 - OS: [docker]
 - Installation [quay.io/biocontainers/gimmemotifs:0.14.4--py37h516909a_0]
 - Version [genomepy, version 0.7.2]

**Additional context**
I tried to exec into container and run those commands:
`genomepy install hg38 UCSC --annotation`
`ls /root/.local/share/genomes/hg38/`
result: directory was empty

**Comment by simonvh** [comment]
Thanks for reporting this. I will look into it. I suspect it has to do with where files will be installed relative to the docker container.

**Comment by simonvh** [comment]
Can you try running the following:

```
# Create a gimmemotifs directory on your normal system
mkdir /home/simon/gimmemotifs

# now connect this to your docker instance
docker run -v /home/simon/gimmemotifs:/root/  /abs/path-it quay.io/biocontainers/gimmemotifs:0.14.4--py37h516909a_0 genomepy install hg38 UCSC --annotation
```

Now this directory `/home/simon/gimmemotifs` (replace with whatever you want) will store all data related to `genomepy` and `gimmemotifs`. A `.local/share/genomes` directory for the genome data, a `.config` directory for configuration files and a `.cache` directory for caching.

**Comment by plachta11b** [comment]
I tried it with mounting root folder without success:
`docker run -v $(realpath gimmemotifs):/root/ -it quay.io/biocontainers/gimmemotifs:0.14.4--py37h516909a_0 genomepy install hg38 UCSC --annotation` (mounted folder still empty)

**Storage should not be issue**
I know docker does not hold persistent storage between runs but this fail in single run.
By "exec into container" i mean: `docker run -v $(realpath gimmemotifs):/root/ -it quay.io/biocontainers/gimmemotifs:0.14.4--py37h516909a_0 sh` and pasting all commands so it is single run and storage does not change.

**Comment by simonvh** [comment]
You're right, when you run all commands within the container non-persistent storage is not an issue. I've checked, and it is an issue with the `genomepy` package. I'll update the build when this is fixed.
