### ISSUE TITLE
Use of -g with FASTA results in: ERROR: Genome file *.fa.sizes does not exist

### ISSUE THREAD

**Issue by plachta11b** [vanheeringen-lab/gimmemotifs#116]
**Describe the bug**
Gimme does not generate genome.fa.sizes file for file specified in -g.

This does not seems to be true: "...you can now also directly supply a genome FASTA instead of a genome name. Pre-indexing is not required anymore."

**To Reproduce**
$genome=Homo_sapiens.GRCh38.dna.primary_assembly.fa (ftp://ftp.ensembl.org/pub/release-100/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz)

$fasta_primary=
> \>ENSG00000165973|ENSG00000165973.19|ENST00000357134|ENST00000357134.10
> ACCCGGCGCTGC....
> \>ENSG00000165973|ENSG00000165973.19|ENST00000325319|ENST00000325319.9
> GGGGCTGCCTTCC....
> \>ENSG00000172020|ENSG00000172020.13|ENST00000305124|ENST00000305124.11
> ACAGTTGCTGCT....

....
```
wc -l 176
wc -c 29408
```

$fasta_background= (similar to primary)
```
wc -l 1550
wc -c 260202
```

In case of manually generated .sizes file gimme freezes. I do not know if it is another issue or badly generated sizes file.
`gimme motifs $fasta_primary /output -g $genome --denovo -b $fasta_background
`

**Expected behavior**
Using consensus fasta file without need for indexing. Gimme not freezing.

**Error logs**
> ERROR: Genome file "/genome/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa.sizes" does not exist

<details>
  <summary>Traceback</summary>
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/prediction.py", line 54, in mp_calc_stats
    genome=genome,
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/stats.py", line 226, in calc_stats
    gc=gc,
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/stats.py", line 121, in calc_stats_iterator
    s.set_meanstd(gc=gc)
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 623, in set_meanstd
    self.set_background(gc=gc)
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 748, in set_background
    tmp.name, genome, number=nseq, length=size, bins=gc_bins
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/background.py", line 398, in gc_bin_bedfile
    create_gc_bin_index(genome, fname, min_bin_size=min_bin_size)
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/background.py", line 330, in create_gc_bin_index
    pybedtools.BedTool().window_maker(g=sizes, w=min_bin_size).nucleotide_content(
  File "/usr/local/lib/python3.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pybedtools/bedtool.py", line 335, in wrapped
    kwargs = self.check_genome(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/pybedtools/bedtool.py", line 1623, in check_genome
    raise FileNotFoundError(msg)
FileNotFoundError: Genome file "/genome/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa.sizes" does not exist
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/commands/motifs.py", line 94, in motifs
    "size": args.size,
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/denovo.py", line 619, in gimme_motifs
    stats_bg=background,
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/prediction.py", line 372, in predict_motifs
    stats_bg=stats_bg,
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/prediction.py", line 320, in pp_predict_motifs
    result.wait_for_stats()
  File "/usr/local/lib/python3.7/site-packages/gimmemotifs/prediction.py", line 178, in wait_for_stats
    job.get()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: Genome file "/genome/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa.sizes" does not exist
</details>

**Installation information (please complete the following information):**
 - OS: [docker]
 - Installation [quay.io/biocontainers/gimmemotifs:0.14.4--py37h516909a_0]
 - Version [GimmeMotifs v0.14.4]

**Additional context**
I tried generate .fa.sizes file manually. Gimme freeze after that.

$genome.sizes= generated by this script
```
from pyfaidx import Fasta
import os
import sys

def sizes_file(fname):
    if not os.path.exists(fname+".sizes"):
        generate_fa_sizes(fname, fname+".sizes")

def generate_fa_sizes(fname, outname):
    f = Fasta(fname)
    with open(outname, "w") as sizes:
        for seqname, seq in f.items():
            sizes.write(f"{seqname}\t{len(seq)}\n")

sizes_file(sys.argv[1])

```

Runs more than 12h without progress.
Last message in .log file is:
> gimme.scanner - DEBUG - using background: genome /genome/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa with size 200

**Comment by simonvh** [comment]
It seems you're running into all kinds of bugs! Sorry for that. The sizes file is something that is fixed in an upstream package, and will be released in a new build. It will then be auto-generated.

The second is a litte bit more difficul for me to assess. How large is your input file, as in number of regions?

**Comment by plachta11b** [comment]
There is no need to apologise. I am happy that this tool is well maintained. I have 88 5utr sequences in primary fasta and 775 5utr sequences in background set downloaded from biomart and as -g I used reference file from ensemble which is 1G large file.
<details><summary>genome.fa</summary>

\>1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF
\>10 dna:chromosome chromosome:GRCh38:10:1:133797422:1 REF
\>11 dna:chromosome chromosome:GRCh38:11:1:135086622:1 REF
\>12 dna:chromosome chromosome:GRCh38:12:1:133275309:1 REF
\>13 dna:chromosome chromosome:GRCh38:13:1:114364328:1 REF
\>14 dna:chromosome chromosome:GRCh38:14:1:107043718:1 REF
\>15 dna:chromosome chromosome:GRCh38:15:1:101991189:1 REF
\>16 dna:chromosome chromosome:GRCh38:16:1:90338345:1 REF
\>17 dna:chromosome chromosome:GRCh38:17:1:83257441:1 REF
\>18 dna:chromosome chromosome:GRCh38:18:1:80373285:1 REF
\>19 dna:chromosome chromosome:GRCh38:19:1:58617616:1 REF
\>2 dna:chromosome chromosome:GRCh38:2:1:242193529:1 REF
\>20 dna:chromosome chromosome:GRCh38:20:1:64444167:1 REF
\>21 dna:chromosome chromosome:GRCh38:21:1:46709983:1 REF
\>22 dna:chromosome chromosome:GRCh38:22:1:50818468:1 REF
\>3 dna:chromosome chromosome:GRCh38:3:1:198295559:1 REF
\>4 dna:chromosome chromosome:GRCh38:4:1:190214555:1 REF
\>5 dna:chromosome chromosome:GRCh38:5:1:181538259:1 REF
\>6 dna:chromosome chromosome:GRCh38:6:1:170805979:1 REF
\>7 dna:chromosome chromosome:GRCh38:7:1:159345973:1 REF
\>8 dna:chromosome chromosome:GRCh38:8:1:145138636:1 REF
\>9 dna:chromosome chromosome:GRCh38:9:1:138394717:1 REF
\>MT dna:chromosome chromosome:GRCh38:MT:1:16569:1 REF
\>X dna:chromosome chromosome:GRCh38:X:1:156040895:1 REF
\>Y dna:chromosome chromosome:GRCh38:Y:2781480:56887902:1 REF
\>KI270728.1 dna:scaffold scaffold:GRCh38:KI270728.1:1:1872759:1 REF
\>KI270727.1 dna:scaffold scaffold:GRCh38:KI270727.1:1:448248:1 REF
\>KI270442.1 dna:scaffold scaffold:GRCh38:KI270442.1:1:392061:1 REF
\>KI270729.1 dna:scaffold scaffold:GRCh38:KI270729.1:1:280839:1 REF
\>GL000225.1 dna:scaffold scaffold:GRCh38:GL000225.1:1:211173:1 REF
\>KI270743.1 dna:scaffold scaffold:GRCh38:KI270743.1:1:210658:1 REF
\>GL000008.2 dna:scaffold scaffold:GRCh38:GL000008.2:1:209709:1 REF
\>GL000009.2 dna:scaffold scaffold:GRCh38:GL000009.2:1:201709:1 REF
\>KI270747.1 dna:scaffold scaffold:GRCh38:KI270747.1:1:198735:1 REF
\>KI270722.1 dna:scaffold scaffold:GRCh38:KI270722.1:1:194050:1 REF
\>GL000194.1 dna:scaffold scaffold:GRCh38:GL000194.1:1:191469:1 REF
\>KI270742.1 dna:scaffold scaffold:GRCh38:KI270742.1:1:186739:1 REF
\>GL000205.2 dna:scaffold scaffold:GRCh38:GL000205.2:1:185591:1 REF
\>GL000195.1 dna:scaffold scaffold:GRCh38:GL000195.1:1:182896:1 REF
\>KI270736.1 dna:scaffold scaffold:GRCh38:KI270736.1:1:181920:1 REF
\>KI270733.1 dna:scaffold scaffold:GRCh38:KI270733.1:1:179772:1 REF
\>GL000224.1 dna:scaffold scaffold:GRCh38:GL000224.1:1:179693:1 REF
\>GL000219.1 dna:scaffold scaffold:GRCh38:GL000219.1:1:179198:1 REF
\>KI270719.1 dna:scaffold scaffold:GRCh38:KI270719.1:1:176845:1 REF
\>GL000216.2 dna:scaffold scaffold:GRCh38:GL000216.2:1:176608:1 REF
\>KI270712.1 dna:scaffold scaffold:GRCh38:KI270712.1:1:176043:1 REF
\>KI270706.1 dna:scaffold scaffold:GRCh38:KI270706.1:1:175055:1 REF
\>KI270725.1 dna:scaffold scaffold:GRCh38:KI270725.1:1:172810:1 REF
\>KI270744.1 dna:scaffold scaffold:GRCh38:KI270744.1:1:168472:1 REF
\>KI270734.1 dna:scaffold scaffold:GRCh38:KI270734.1:1:165050:1 REF
\>GL000213.1 dna:scaffold scaffold:GRCh38:GL000213.1:1:164239:1 REF
\>GL000220.1 dna:scaffold scaffold:GRCh38:GL000220.1:1:161802:1 REF
\>KI270715.1 dna:scaffold scaffold:GRCh38:KI270715.1:1:161471:1 REF
\>GL000218.1 dna:scaffold scaffold:GRCh38:GL000218.1:1:161147:1 REF
\>KI270749.1 dna:scaffold scaffold:GRCh38:KI270749.1:1:158759:1 REF
\>KI270741.1 dna:scaffold scaffold:GRCh38:KI270741.1:1:157432:1 REF
\>GL000221.1 dna:scaffold scaffold:GRCh38:GL000221.1:1:155397:1 REF
\>KI270716.1 dna:scaffold scaffold:GRCh38:KI270716.1:1:153799:1 REF
\>KI270731.1 dna:scaffold scaffold:GRCh38:KI270731.1:1:150754:1 REF
\>KI270751.1 dna:scaffold scaffold:GRCh38:KI270751.1:1:150742:1 REF
\>KI270750.1 dna:scaffold scaffold:GRCh38:KI270750.1:1:148850:1 REF
\>KI270519.1 dna:scaffold scaffold:GRCh38:KI270519.1:1:138126:1 REF
\>GL000214.1 dna:scaffold scaffold:GRCh38:GL000214.1:1:137718:1 REF
\>KI270708.1 dna:scaffold scaffold:GRCh38:KI270708.1:1:127682:1 REF
\>KI270730.1 dna:scaffold scaffold:GRCh38:KI270730.1:1:112551:1 REF
\>KI270438.1 dna:scaffold scaffold:GRCh38:KI270438.1:1:112505:1 REF
\>KI270737.1 dna:scaffold scaffold:GRCh38:KI270737.1:1:103838:1 REF
\>KI270721.1 dna:scaffold scaffold:GRCh38:KI270721.1:1:100316:1 REF
\>KI270738.1 dna:scaffold scaffold:GRCh38:KI270738.1:1:99375:1 REF
\>KI270748.1 dna:scaffold scaffold:GRCh38:KI270748.1:1:93321:1 REF
\>KI270435.1 dna:scaffold scaffold:GRCh38:KI270435.1:1:92983:1 REF
\>GL000208.1 dna:scaffold scaffold:GRCh38:GL000208.1:1:92689:1 REF
\>KI270538.1 dna:scaffold scaffold:GRCh38:KI270538.1:1:91309:1 REF
\>KI270756.1 dna:scaffold scaffold:GRCh38:KI270756.1:1:79590:1 REF
\>KI270739.1 dna:scaffold scaffold:GRCh38:KI270739.1:1:73985:1 REF
\>KI270757.1 dna:scaffold scaffold:GRCh38:KI270757.1:1:71251:1 REF
\>KI270709.1 dna:scaffold scaffold:GRCh38:KI270709.1:1:66860:1 REF
\>KI270746.1 dna:scaffold scaffold:GRCh38:KI270746.1:1:66486:1 REF
\>KI270753.1 dna:scaffold scaffold:GRCh38:KI270753.1:1:62944:1 REF
\>KI270589.1 dna:scaffold scaffold:GRCh38:KI270589.1:1:44474:1 REF
\>KI270726.1 dna:scaffold scaffold:GRCh38:KI270726.1:1:43739:1 REF
\>KI270735.1 dna:scaffold scaffold:GRCh38:KI270735.1:1:42811:1 REF
\>KI270711.1 dna:scaffold scaffold:GRCh38:KI270711.1:1:42210:1 REF
\>KI270745.1 dna:scaffold scaffold:GRCh38:KI270745.1:1:41891:1 REF
\>KI270714.1 dna:scaffold scaffold:GRCh38:KI270714.1:1:41717:1 REF
\>KI270732.1 dna:scaffold scaffold:GRCh38:KI270732.1:1:41543:1 REF
\>KI270713.1 dna:scaffold scaffold:GRCh38:KI270713.1:1:40745:1 REF
\>KI270754.1 dna:scaffold scaffold:GRCh38:KI270754.1:1:40191:1 REF
\>KI270710.1 dna:scaffold scaffold:GRCh38:KI270710.1:1:40176:1 REF
\>KI270717.1 dna:scaffold scaffold:GRCh38:KI270717.1:1:40062:1 REF
\>KI270724.1 dna:scaffold scaffold:GRCh38:KI270724.1:1:39555:1 REF
\>KI270720.1 dna:scaffold scaffold:GRCh38:KI270720.1:1:39050:1 REF
\>KI270723.1 dna:scaffold scaffold:GRCh38:KI270723.1:1:38115:1 REF
\>KI270718.1 dna:scaffold scaffold:GRCh38:KI270718.1:1:38054:1 REF
\>KI270317.1 dna:scaffold scaffold:GRCh38:KI270317.1:1:37690:1 REF
\>KI270740.1 dna:scaffold scaffold:GRCh38:KI270740.1:1:37240:1 REF
\>KI270755.1 dna:scaffold scaffold:GRCh38:KI270755.1:1:36723:1 REF
\>KI270707.1 dna:scaffold scaffold:GRCh38:KI270707.1:1:32032:1 REF
\>KI270579.1 dna:scaffold scaffold:GRCh38:KI270579.1:1:31033:1 REF
\>KI270752.1 dna:scaffold scaffold:GRCh38:KI270752.1:1:27745:1 REF
\>KI270512.1 dna:scaffold scaffold:GRCh38:KI270512.1:1:22689:1 REF
\>KI270322.1 dna:scaffold scaffold:GRCh38:KI270322.1:1:21476:1 REF
\>GL000226.1 dna:scaffold scaffold:GRCh38:GL000226.1:1:15008:1 REF
\>KI270311.1 dna:scaffold scaffold:GRCh38:KI270311.1:1:12399:1 REF
\>KI270366.1 dna:scaffold scaffold:GRCh38:KI270366.1:1:8320:1 REF
\>KI270511.1 dna:scaffold scaffold:GRCh38:KI270511.1:1:8127:1 REF
\>KI270448.1 dna:scaffold scaffold:GRCh38:KI270448.1:1:7992:1 REF
\>KI270521.1 dna:scaffold scaffold:GRCh38:KI270521.1:1:7642:1 REF
\>KI270581.1 dna:scaffold scaffold:GRCh38:KI270581.1:1:7046:1 REF
\>KI270582.1 dna:scaffold scaffold:GRCh38:KI270582.1:1:6504:1 REF
\>KI270515.1 dna:scaffold scaffold:GRCh38:KI270515.1:1:6361:1 REF
\>KI270588.1 dna:scaffold scaffold:GRCh38:KI270588.1:1:6158:1 REF
\>KI270591.1 dna:scaffold scaffold:GRCh38:KI270591.1:1:5796:1 REF
\>KI270522.1 dna:scaffold scaffold:GRCh38:KI270522.1:1:5674:1 REF
\>KI270507.1 dna:scaffold scaffold:GRCh38:KI270507.1:1:5353:1 REF
\>KI270590.1 dna:scaffold scaffold:GRCh38:KI270590.1:1:4685:1 REF
\>KI270584.1 dna:scaffold scaffold:GRCh38:KI270584.1:1:4513:1 REF
\>KI270320.1 dna:scaffold scaffold:GRCh38:KI270320.1:1:4416:1 REF
\>KI270382.1 dna:scaffold scaffold:GRCh38:KI270382.1:1:4215:1 REF
\>KI270468.1 dna:scaffold scaffold:GRCh38:KI270468.1:1:4055:1 REF
\>KI270467.1 dna:scaffold scaffold:GRCh38:KI270467.1:1:3920:1 REF
\>KI270362.1 dna:scaffold scaffold:GRCh38:KI270362.1:1:3530:1 REF
\>KI270517.1 dna:scaffold scaffold:GRCh38:KI270517.1:1:3253:1 REF
\>KI270593.1 dna:scaffold scaffold:GRCh38:KI270593.1:1:3041:1 REF
\>KI270528.1 dna:scaffold scaffold:GRCh38:KI270528.1:1:2983:1 REF
\>KI270587.1 dna:scaffold scaffold:GRCh38:KI270587.1:1:2969:1 REF
\>KI270364.1 dna:scaffold scaffold:GRCh38:KI270364.1:1:2855:1 REF
\>KI270371.1 dna:scaffold scaffold:GRCh38:KI270371.1:1:2805:1 REF
\>KI270333.1 dna:scaffold scaffold:GRCh38:KI270333.1:1:2699:1 REF
\>KI270374.1 dna:scaffold scaffold:GRCh38:KI270374.1:1:2656:1 REF
\>KI270411.1 dna:scaffold scaffold:GRCh38:KI270411.1:1:2646:1 REF
\>KI270414.1 dna:scaffold scaffold:GRCh38:KI270414.1:1:2489:1 REF
\>KI270510.1 dna:scaffold scaffold:GRCh38:KI270510.1:1:2415:1 REF
\>KI270390.1 dna:scaffold scaffold:GRCh38:KI270390.1:1:2387:1 REF
\>KI270375.1 dna:scaffold scaffold:GRCh38:KI270375.1:1:2378:1 REF
\>KI270420.1 dna:scaffold scaffold:GRCh38:KI270420.1:1:2321:1 REF
\>KI270509.1 dna:scaffold scaffold:GRCh38:KI270509.1:1:2318:1 REF
\>KI270315.1 dna:scaffold scaffold:GRCh38:KI270315.1:1:2276:1 REF
\>KI270302.1 dna:scaffold scaffold:GRCh38:KI270302.1:1:2274:1 REF
\>KI270518.1 dna:scaffold scaffold:GRCh38:KI270518.1:1:2186:1 REF
\>KI270530.1 dna:scaffold scaffold:GRCh38:KI270530.1:1:2168:1 REF
\>KI270304.1 dna:scaffold scaffold:GRCh38:KI270304.1:1:2165:1 REF
\>KI270418.1 dna:scaffold scaffold:GRCh38:KI270418.1:1:2145:1 REF
\>KI270424.1 dna:scaffold scaffold:GRCh38:KI270424.1:1:2140:1 REF
\>KI270417.1 dna:scaffold scaffold:GRCh38:KI270417.1:1:2043:1 REF
\>KI270508.1 dna:scaffold scaffold:GRCh38:KI270508.1:1:1951:1 REF
\>KI270303.1 dna:scaffold scaffold:GRCh38:KI270303.1:1:1942:1 REF
\>KI270381.1 dna:scaffold scaffold:GRCh38:KI270381.1:1:1930:1 REF
\>KI270529.1 dna:scaffold scaffold:GRCh38:KI270529.1:1:1899:1 REF
\>KI270425.1 dna:scaffold scaffold:GRCh38:KI270425.1:1:1884:1 REF
\>KI270396.1 dna:scaffold scaffold:GRCh38:KI270396.1:1:1880:1 REF
\>KI270363.1 dna:scaffold scaffold:GRCh38:KI270363.1:1:1803:1 REF
\>KI270386.1 dna:scaffold scaffold:GRCh38:KI270386.1:1:1788:1 REF
\>KI270465.1 dna:scaffold scaffold:GRCh38:KI270465.1:1:1774:1 REF
\>KI270383.1 dna:scaffold scaffold:GRCh38:KI270383.1:1:1750:1 REF
\>KI270384.1 dna:scaffold scaffold:GRCh38:KI270384.1:1:1658:1 REF
\>KI270330.1 dna:scaffold scaffold:GRCh38:KI270330.1:1:1652:1 REF
\>KI270372.1 dna:scaffold scaffold:GRCh38:KI270372.1:1:1650:1 REF
\>KI270548.1 dna:scaffold scaffold:GRCh38:KI270548.1:1:1599:1 REF
\>KI270580.1 dna:scaffold scaffold:GRCh38:KI270580.1:1:1553:1 REF
\>KI270387.1 dna:scaffold scaffold:GRCh38:KI270387.1:1:1537:1 REF
\>KI270391.1 dna:scaffold scaffold:GRCh38:KI270391.1:1:1484:1 REF
\>KI270305.1 dna:scaffold scaffold:GRCh38:KI270305.1:1:1472:1 REF
\>KI270373.1 dna:scaffold scaffold:GRCh38:KI270373.1:1:1451:1 REF
\>KI270422.1 dna:scaffold scaffold:GRCh38:KI270422.1:1:1445:1 REF
\>KI270316.1 dna:scaffold scaffold:GRCh38:KI270316.1:1:1444:1 REF
\>KI270340.1 dna:scaffold scaffold:GRCh38:KI270340.1:1:1428:1 REF
\>KI270338.1 dna:scaffold scaffold:GRCh38:KI270338.1:1:1428:1 REF
\>KI270583.1 dna:scaffold scaffold:GRCh38:KI270583.1:1:1400:1 REF
\>KI270334.1 dna:scaffold scaffold:GRCh38:KI270334.1:1:1368:1 REF
\>KI270429.1 dna:scaffold scaffold:GRCh38:KI270429.1:1:1361:1 REF
\>KI270393.1 dna:scaffold scaffold:GRCh38:KI270393.1:1:1308:1 REF
\>KI270516.1 dna:scaffold scaffold:GRCh38:KI270516.1:1:1300:1 REF
\>KI270389.1 dna:scaffold scaffold:GRCh38:KI270389.1:1:1298:1 REF
\>KI270466.1 dna:scaffold scaffold:GRCh38:KI270466.1:1:1233:1 REF
\>KI270388.1 dna:scaffold scaffold:GRCh38:KI270388.1:1:1216:1 REF
\>KI270544.1 dna:scaffold scaffold:GRCh38:KI270544.1:1:1202:1 REF
\>KI270310.1 dna:scaffold scaffold:GRCh38:KI270310.1:1:1201:1 REF
\>KI270412.1 dna:scaffold scaffold:GRCh38:KI270412.1:1:1179:1 REF
\>KI270395.1 dna:scaffold scaffold:GRCh38:KI270395.1:1:1143:1 REF
\>KI270376.1 dna:scaffold scaffold:GRCh38:KI270376.1:1:1136:1 REF
\>KI270337.1 dna:scaffold scaffold:GRCh38:KI270337.1:1:1121:1 REF
\>KI270335.1 dna:scaffold scaffold:GRCh38:KI270335.1:1:1048:1 REF
\>KI270378.1 dna:scaffold scaffold:GRCh38:KI270378.1:1:1048:1 REF
\>KI270379.1 dna:scaffold scaffold:GRCh38:KI270379.1:1:1045:1 REF
\>KI270329.1 dna:scaffold scaffold:GRCh38:KI270329.1:1:1040:1 REF
\>KI270419.1 dna:scaffold scaffold:GRCh38:KI270419.1:1:1029:1 REF
\>KI270336.1 dna:scaffold scaffold:GRCh38:KI270336.1:1:1026:1 REF
\>KI270312.1 dna:scaffold scaffold:GRCh38:KI270312.1:1:998:1 REF
\>KI270539.1 dna:scaffold scaffold:GRCh38:KI270539.1:1:993:1 REF
\>KI270385.1 dna:scaffold scaffold:GRCh38:KI270385.1:1:990:1 REF
\>KI270423.1 dna:scaffold scaffold:GRCh38:KI270423.1:1:981:1 REF
\>KI270392.1 dna:scaffold scaffold:GRCh38:KI270392.1:1:971:1 REF
\>KI270394.1 dna:scaffold scaffold:GRCh38:KI270394.1:1:970:1 REF
</details>

I will test new version of genomepy. Maybe its caused by invalid .sizes file

**Comment by plachta11b** [comment]
I tested your fix in develop branch and it successfully create .sizes file and gap file as a bonus too. Here is dockerfile in case someone would need update container to latest genomepy.
```
FROM alpine/git:latest AS builder

WORKDIR /
RUN git clone https://github.com/vanheeringen-lab/genomepy.git
RUN git -C /genomepy checkout develop

FROM quay.io/biocontainers/gimmemotifs:0.14.4--py37h516909a_0

COPY --from=builder /genomepy /genomepy

RUN pip install /genomepy
```
Main issue solved but container still hangs. I will open new issue for that. Thank you for fast fix.
