### ISSUE TITLE
Sensitivity cutoff for motif identification?

### ISSUE THREAD

**Issue by ClarissaFeuersteinAkgoz** [vanheeringen-lab/gimmemotifs#120]
Is there a way to set the sentivity of identifying a sequence as a motif?
GimmeMotifs seems to have a very stringent way of selecting motifs.

**Comment by simonvh** [comment]
Depends on your specific question :)  Is this when using `gimme motifs`? Or when scanning? A threshold that is used in many of the GimmeMotifs tools is a 1% FPR.  This means that it selects the motif cutoff that would result in 1% hits in the background. However, the choice of threshold can vary, depending on your application. If you can explain a little bit more, I can try to help you with selecting the optimal approach.

**Comment by ClarissaFeuersteinAkgoz** [comment]
It is when using gimme motifs on known motifs. But after identifying the significantly enriched motifs I  want to work with the identified intervals that have this motif (file that is generated with gimme motifs for the non reduntant motifs)

**Comment by simonvh** [comment]
Ah. I see. At the moment there is indeed no easy way to use specifically these motifs for scanning. 
Here is a workaround. In your gimmemotifs output directory, run the following command to get a file with a list of the non-redundant motif ids:

```
cat motif_scan_results/*bed | grep -v \# |cut -f4 | sort -u > motif_ids.txt
```

Then, save the following python code as `filter_motifs.py`:

```
#!/usr/bin/env python
from gimmemotifs.motif import read_motifs
from optparse import OptionParser
import sys

VERSION = "0.1"

parser = OptionParser(version="%prog " + VERSION)
parser.add_option("-p", "--pfmfile", dest="pfmfile", help="Motifs in PFM format", metavar="FILE")
parser.add_option("-i", "--inputfile", dest="inputfile", help="List of motif IDs in text file", metavar="FILE")

(options, args) = parser.parse_args()

if not options.inputfile:
    parser.print_help()
    sys.exit()

motifs = read_motifs(options.pwmfile)
ids = [line.strip().split("\t")[0] for line in open(options.inputfile)]

for motif in [m for m in motifs if m.id.split("\t")[0] in ids]:
    print(motif.to_pfm())
```

You can now get the non-redundant motifs with:

```
# if you use the default motif database
python filter_motifs.py -i motif_ids.txt > non-redundant.pfm

# with another motif database
python filter_motifs.py -p <motif_db> -i motif_ids.txt > non-redundant.pfm
```

Now you can use `gimme scan` and specify the threshold that you want:

```
# default, 1% FPR
gimme scan <input> -p non-redundant.pfm  -g hg39 -b > out.bed

# more lenient, 5% FPR
gimme scan <input> -p non-redundant.pfm  -g hg39 -b -f 0.05 > out.bed
```

**Comment by ClarissaFeuersteinAkgoz** [comment]
Thank you very much for searching for a solution! 
I followed your suggestions and when running filter_motifs.py I get the following Error message: 

(gimme100) -bash-4.2$ python filter_motifs.py -i motif_ids.txt > non-redundant.pfm
Traceback (most recent call last):
  File "filter_motifs.py", line 18, in <module>
    motifs = read_motifs(options.pwmfile)
AttributeError: 'Values' object has no attribute 'pwmfile'

The same happens if I run it on an analysis with hocomoco motifs:

(gimme100) -bash-4.2$ python filter_motifs.py -p HOCOMOCOv11_HUMAN -i motif_ids.txt > non-redundant.pfm
Traceback (most recent call last):
  File "filter_motifs.py", line 18, in <module>
    motifs = read_motifs(options.pwmfile)
AttributeError: 'Values' object has no attribute 'pwmfile'

Can you help once more?
Thanks a lot!

**Comment by simonvh** [comment]
Ah sorry!

This line:

```
motifs = read_motifs(options.pwmfile)
```

should be:

```
motifs = read_motifs(options.pfmfile)
```

**Comment by ClarissaFeuersteinAkgoz** [comment]
yes that worked! great! thanks!

**Comment by ClarissaFeuersteinAkgoz** [comment]
when using these commands, then it uses random regions of the genome to calculate 1% or 5% FPR, right? I works nicely.

#84 default, 1% FPR
gimme scan <input> -p non-redundant.pfm  -g hg19 -b > out.bed

# more lenient, 5% FPR
gimme scan <input> -p non-redundant.pfm  -g hg19 -b -f 0.05 > out.bed

When I want to use my own background for this analysis, I tried to run: 

gimme scan <input> -p non-redundant.pfm  -g hg19 -B <background> -b -f 0.05 > out.bed

then I get following error message:
Traceback (most recent call last):
  File "/home/feuerste/miniconda3/envs/gimme100/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/commands/pfmscan.py", line 36, in pfmscan
    gcnorm=args.gcnorm,
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 306, in scan_to_file
    gcnorm=gcnorm,
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 199, in command_scan
    genome=genome, fname=bgfile, size=fa.median_length(), gc=gcnorm
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 709, in set_background
    raise ValueError("Need either genome or filename for background.")
ValueError: Need either genome or filename for background.


I tried also just giving the background without the genome: 

gimme scan <input> -p non-redundant.pfm  -B <background> -b -f 0.05 > out.bed

then I get the following error message: 

Traceback (most recent call last):
  File "/home/feuerste/miniconda3/envs/gimme100/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/commands/pfmscan.py", line 36, in pfmscan
    gcnorm=args.gcnorm,
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 306, in scan_to_file
    gcnorm=gcnorm,
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 188, in command_scan
    fa = as_fasta(inputfile, genome)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimmemotifs/utils.py", line 510, in as_fasta
    raise ValueError("need genome to convert to FASTA")
ValueError: need genome to convert to FASTA

How can I use correctly the background specification -B in the gimme scan function?

**Comment by simonvh** [comment]
Yes, it used random regions from the genome. If you specify the `--gc` parameter, the sequences will have a similar GC% distribution as your input file.

At the moment it's not possible to use BED files as a custom background. I will add this to the todo for next version!
