### ISSUE TITLE
TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'numpy.ndarray'

### ISSUE THREAD

**Issue by ClarissaFeuersteinAkgoz** [vanheeringen-lab/gimmemotifs#123]
When I run the following command: 
gimme motifs -b bg_gain_LMR_p0.005.bed -g hg19 --known -p HOCOMOCOv11_HUMAN gain_LMR_p0.005.bed ./result_interval

with a different bed file it has worked already

I get the following error message

**Error logs**
2020-06-23 12:29:17,592 - INFO - skipping de novo
2020-06-23 12:29:17,598 - INFO - creating motif scan tables
2020-06-23 12:33:05,535 - INFO - calculating stats
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.443388' '1.6809939999999999' '-0.215752']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.979627' '0.550293' '0.6340359999999999']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.39129' '0.761863' '-0.039827']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '3.2660259999999997' '0.39620700000000003'
 '-0.112055']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.395746' '-0.43999099999999997'
 '1.3514190000000001']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.011143' '1.28257' '-2.907377']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.135723' '0.234121' '-1.4247100000000001']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.1872770000000001' '1.1870100000000001'
 '-2.015707']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.011606' '-0.11078800000000001'
 '0.7163689999999999']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.728649' '0.126275' '0.9604389999999999']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.25085' '0.110528' '0.624474']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.813901' '0.760238' '-0.42581']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.649544' '0.07642' '0.054885']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.983754' '-0.073076' '-2.099869']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.738653' '2.2022310000000003' '-1.910455']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.549878' '1.0428709999999999' '0.389892']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.8479959999999999' '1.422683'
 '-1.2352379999999998']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.73747' '0.474498' '-1.3959620000000001']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.506909' '0.047011000000000004' '-0.775601']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.8984770000000001' '0.23693699999999998'
 '-0.48547700000000005']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.08025700000000001' '0.5408189999999999'
 '-0.940793']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.178784' '1.321532' '-1.420401']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.269354' '1.1403590000000001' '-0.08666']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.37740100000000004' '0.710505'
 '0.9121370000000001']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.6333880000000001' '1.353281' '-2.812048']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.041668000000000004' '0.6511319999999999'
 '-2.909601']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.023979' '-0.143623' '0.995693']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.42371000000000003' '2.109898' '1.045691']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.8099890000000001' '0.894804' '0.965268']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.663554' '0.747246' '1.504478']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.491808' '-0.258295' '-1.023865']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.702937' '1.077391' '-1.160859']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.103699' '0.33116999999999996' '0.03873']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.037225' '1.7343819999999999' '-1.834514']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.060799' '-0.015401' '0.7291270000000001']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.236355' '1.1763219999999999' '-0.395504']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.9637629999999999' '2.476746'
 '1.8968049999999999']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.694009' '1.032813' '-2.4005080000000003']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.1497080000000004' '1.653673' '-2.392806']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.20135' '1.354429' '-1.6896669999999998']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.13836400000000001' '0.702538' '2.415279']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.868002' '1.3102770000000001' '-1.58334']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.015258' '1.446137' '0.09663200000000001']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.116437' '0.521487' '1.629353']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.479708' '0.398408' '-0.30362']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.018628' '1.376119' '-0.539283']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.659251' '0.8953979999999999'
 '0.48822600000000005']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.14846199999999998' '0.404319'
 '-0.49439700000000003']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.4632120000000002' '0.6114430000000001'
 '-1.258268']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.2362229999999998' '0.057651999999999995'
 '2.183386']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.807552' '0.5102300000000001'
 '-0.5469149999999999']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.636939' '0.216392' '1.127918']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.0573110000000001' '-0.482809' '-0.291158']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.790679' '0.750173' '0.41952399999999995']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.823967' '1.162166' '-1.0355290000000001']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.101901' '0.742175' '-0.5546270000000001']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.495072' '0.601418' '-1.3896950000000001']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.100002' '1.32155' '0.143701']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.218116' '0.370867' '-0.869878']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.460449' '1.154191' '-2.3277919999999996']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '1.86558' '0.11198699999999999' '-2.79482']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '-0.051824' '0.638926' '-1.529782']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.502598' '1.2112610000000001' '-1.939114']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.49585100000000004' '1.7229279999999998'
 '-0.8115319999999999']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.28885900000000003' '-0.069594' '1.984647']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '2.081008' '2.109893' '-1.19423']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
[1. 1. 1. ... 0. 0. 0.]
[' nan' ' nan' ' nan' ... '0.5998020000000001' '0.0065260000000000006'
 '0.46625500000000003']
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/feuerste/miniconda3/envs/gimme101/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/feuerste/miniconda3/envs/gimme101/lib/python3.7/site-packages/gimmemotifs/rocmetrics.py", line 165, in phyper_at_fpr
    [sum(fg_vals >= s), sum(bg_vals >= s)],
TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'numpy.ndarray'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/feuerste/miniconda3/envs/gimme101/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/feuerste/miniconda3/envs/gimme101/lib/python3.7/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/home/feuerste/miniconda3/envs/gimme101/lib/python3.7/site-packages/gimmemotifs/commands/motifs.py", line 183, in motifs
    ncpus=args.ncpus,
  File "/home/feuerste/miniconda3/envs/gimme101/lib/python3.7/site-packages/gimmemotifs/stats.py", line 160, in calc_stats_iterator
    for motif_id, s, ret in it:
  File "/home/feuerste/miniconda3/envs/gimme101/lib/python3.7/site-packages/gimmemotifs/stats.py", line 284, in _mp_stats
    ret = job.get()
  File "/home/feuerste/miniconda3/envs/gimme101/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'numpy.ndarray'

**Installation information (please complete the following information):**
 - Linux
 - Installation  with miniconda
 - Version conda 4.8.2

**Additional context**

**Comment by ClarissaFeuersteinAkgoz** [comment]
I know what the problem was! Intervals were size of 1bp

**Comment by simonvh** [comment]
Thanks for letting me know (and sorry for the delay in replying). This is something that should also be fixed, with a warning or something.
