### ISSUE TITLE
gimme motifs pyfaidx.FetchError

### ISSUE THREAD

**Issue by wangmhan** [vanheeringen-lab/gimmemotifs#130]
Hi, 

I tried to run gimme motifs, and it end with error.

My steps:
genomepy install ftp://ftp.ensembl.org/pub/release-97/fasta/gallus_gallus/dna/Gallus_gallus.GRCg6a.dna_sm.toplevel.fa.gz url --localname gg6_ensembl97
ln -s ~/references/ens_g6_atac/Gg6_extended_200819.filter.gtf 
gimme motifs -N 8 -p JASPAR2020_vertebrates -g gg6_ensembl97 in.bed out_dir

I attached the error log.

**Installation information (please complete the following information):**
 - OS: CentOS 7.8
 - Installation: conda install gimmemotifs
 - Version 0.14.4
genomepy --version 0.8.3

[slurm-13091988.out.txt](https://github.com/vanheeringen-lab/gimmemotifs/files/4895907/slurm-13091988.out.txt)

**Comment by siebrenf** [comment]
Hey @wangmhan, 

I'm no expert on `pyfaidx` or `gimme`, but if I read your log correctly `pyfaidx` cannot find chromosome 28.

Looking at the `gg6_ensembl97.fa.sizes` file we see `28      5116882`, so it is present in your genome.
Tracing the error further back, we see function `prepare_denovo_input_bed` was called. So my hypothesis is that `in.bed` does not contain the chromosome. Perhaps it is called `chr28` in the bed file? (note I don't even know if it has to be in the bed file)

Alternatively and slightly more complicatedly, @simonvh, the error reads:
`"Requested rname 28	1899108	1899308	28 does not exist!"`. 
In the pyfaidx code this is written as:
`"Requested rname {0} does not exist!".format(rname)`

So it could be that the sequence is parsed incorrectly? [Here's the pyfaidx function](https://github.com/mdshw5/pyfaidx/blob/2c9f369f98c847df5b907cfee1ae3bf36c18f33f/pyfaidx/__init__.py#L639).

**Comment by wangmhan** [comment]
Hi Seibrenf,

There is no chr as prefix in bed files, as I also use Ensembl genome when call peaks.
the bed file looks like this:
2       137220997       137222121       2:137220997-137222121
1       118197558       118198419       1:118197558-118198419
2       135379155       135380077       2:135379155-135380077
1       88023060        88024016        1:88023060-88024016
2       142106184       142108062       2:142106184-142108062

Also, I am not sure if the problem is specific to chromosome 28, as I run several times, it also get similar error for chromosome 32:
pyfaidx.FetchError: Requested rname 32  74535   74735   32 does not exist! Please check your FASTA file.

I don't know how to check to see if the sequence is parsed correctly or not...Is there any suggestion for that?

Thanks!

**Comment by simonvh** [comment]
Is the BED file tab-separated?

**Comment by wangmhan** [comment]
Yes, I just double checked. The BED file is tab-separated.

**Comment by simonvh** [comment]
@wangmhan Would it be possible for you to send me your input BED file so I can test locally?

**Comment by wangmhan** [comment]
Yes sure. That would be great!

It is chicken data. Is it possible to attach file here?
Or I should paste all the content?

Thanks a lot!

I attached the BED file. Please let me know if it does not work.

**Comment by wangmhan** [comment]
Hi,

I just attach the file through browser. Hope now it work this time.
[chicken_galgal6.bed.txt](https://github.com/vanheeringen-lab/gimmemotifs/files/4926798/chicken_galgal6.bed.txt)

**Comment by simonvh** [comment]
Thanks! That helps! You've encountered a bug in genomepy. The BED is incorrectly recognized as a region file, because of the peak identifier in the fourth column. For now, if you remove the 4th column, it should run fine. We'll include a fix for this in the next release of genomepy.

**Comment by wangmhan** [comment]
Hi Simonvh,

Thanks for your suggestion! I removed 4th column, and now it runs well.
