### ISSUE TITLE
background usage

### ISSUE THREAD

**Issue by fgualdr** [vanheeringen-lab/gimmemotifs#131]
Hi,

mine is a question as I was comparing results between Gimme Motifs (to check known enrichments) and Homer.
I am providing a BED file with a list of background sites as I am in Homer but for some high GC rich areas results are different which made me wonder whether with gimme motif when I provide background sites there is no GC normalisation of any sort.
am I correct?

Thanks

Francesco

**Comment by simonvh** [comment]
@fgualdr GimmeMotifs in some cases performs GC%-specific z-score transformations. However, it depends a bit on what command you used. Can you give some more specifics?

**Comment by fgualdr** [comment]
The line I'm sending is the following:

gimme motifs $PEAK $FOLDER --size 145 --known --background $BG -g hg38 --nthreads 12 -f 0.8

**Comment by simonvh** [comment]
Thanks for the command. When running `gimme motifs`, by default the motif scores (log-odds based on the PFMs) are z-score normalised based on the background sequences. However, GimmeMotifs does this in a GC%-bin specific manner. For instance, if a sequence is 56% GC, then the z-score transformation is based on the scores of all background sequences with 50-60% GC. This will make a lot of difference for GC-rich motifs (ie. SP1) in high GC% regions. I suspect that if you specify `--rawscore` the results might be more similar to Homer.

A small thing: in the current version there is a bug in the implementation, which makes the FPR% calculation too conservative. This will be updated in the forthcoming release.

**Comment by simonvh** [comment]
Oh, one other note: there is currently a bug with the `--size` option which is ignored for some analyses. This also an issue that will be fixed in the next release.

**Comment by simonvh** [comment]
Note to self: provide a more clear explanation of GC% normalization, how it works, in the docs.
