### ISSUE TITLE
Cross-species comparison

### ISSUE THREAD

**Issue by fransilvion** [vanheeringen-lab/gimmemotifs#141]
Hi!

I have fasta sequences from open regions (same cell lines) from mouse and human. I wonder what would be the best way to do differential motif enrichment analysis of this data with your tool, so I can get motifs that are enriched in mouse compared to human and vice versa? In **gimme motifs**, I can choose my background sequence set but I have to specify the genome (otherwise it gives me an error), and since here I have two genomes (hg19 and mm10) I am not sure how to proceed. There is also **gimme maelstrom** command, but it doesn't take fasta sequences and as I understood here you need to provide different experiments, which are done in the same species. So my question is, what is the best way to analyze my data with your tool?

Thank you!

**Comment by simonvh** [comment]
I think in the current version, `gimme motifs` would be your best bet. The genome is used to calculate a genome-specific FPR. What I would to is run the program in two ways:

`gimme motifs input_human.fa human_vs_mouse -b input_mouse.fa -g hg19`

and

`gimme motifs input_mouse.fa mouse_vs_human -b input_human.fa  -g mm10`

If you would like to use only known motifs and skip *de novo* motif prediction you can add the `--known` argument.

As you have open regions, you likely have many regions. Especially for the `de novo` motif analysis, I would advise to select a random subset (say ~10,000) regions. Many of the tools for motif prediction don't scale very well to large input data.

One other consideration is the fraction of promoters in your two data sets. As the sequence composition is different (more GC-rich sequences), the associated motif will also be different. You could consider analysing species-specific promoter-proximal and promoter-distal elements seperately.

**Comment by simonvh** [comment]
The `develop` branch of gimmemotifs now has initial multi-species support for `gimme maelstrom`. No support yet for FASTA files as that needs a more extensive rewrite of some internal functions. For now the input format is as follows:

```
region  cluster
hg38@chr13:101988239-101988439  human_x
hg38@chr22:49553618-49553818    human_y
mm10@chr10:116371176-116371376  mouse_z
hg38@chr5:141734925-141735125   human_x
mm10@chr2:128261665-128261865   mouse_z
hg38@chr7:142168837-142169037   human_y
mm10@chr18:82872440-82872640    mouse_z
hg38@chr22:23692722-23692922    human_x
hg38@chr16:3170616-3170816      human_x
mm10@chr13:23586453-23586653    mouse_z
```

In this case, three groups are compared: `x`, `y` and `z`. The groups `x` and `y` are human sequences from `hg38`, the `z` group are mouse `mm10` coordinates. For running `gimme maelstrom` you still need to set a genome, which is now only used to calculate background frequencies. These are used to select the FPR threshold for motif occurrences and to z-score normalize and GC% correct the motif scores. This might need to be replaced with a more sophisticated approach in the future.

If you want to try this out (feedback is welcome) you can install the `develop` version of gimmemotifs as follows:

```
conda create -n gimme_dev gimmemotifs
conda activate gimme_dev
pip install git+https://github.com/vanheeringen-lab/gimmemotifs.git@develop
````

**Comment by fransilvion** [comment]
Hi, thank you for your response! That was extremely helpful. I have another question since you mentioned the scaling problem. I noticed that `gimme motifs` takes a lot of time (up to 5 hours) even for small data sets (fasta files with ~500 sequences). Here is the command that I run:

`gimme motifs Population/query.fa -g ../hg19.fa gimme_output_folder` 

What are the potential ways of increasing speed? Thank you!

**Comment by simonvh** [comment]
What is the length of the fasta sequences in `Population/query.fa`? If these are very long, then `gimme motifs` will indeed take a long time. Most of our work is focused on short sequences (TF binding sites, enhancers, promoters, ChIP-seq peaks, etc.), where we usually take sequences of ~100-1000bp. In that case, 500 sequences should not take that long. 
The running time is determined by two things: 1) the *de novo* motif prediction tools. Some of these don't scale that well with longer inputs. You can specifically choose the ones that don't take too long with the `-t` option. 2) For calculating the statistics, a background set of sequences will be used, which will be larger than your input. 

Finally, most of the statistics that `gimme motifs` reports will be based on the maximum score per motif per sequence. This doesn't work that well for longer sequences.

**Comment by fransilvion** [comment]
it's 200 bp, I was expecting it to run pretty fast, but probably the issue was with de novo motif prediction, I should probably omit this part.

**Comment by simonvh** [comment]
If you have a run that you think takes a long time, you can always upload the log file so I can have a look to see if I can spot a problem.

**Comment by simonvh** [comment]
Closing this issue, as it's >6 months. If you do have problems with long running times, please feel free to re-open.
