### ISSUE TITLE
gimme maelstrom error: "TypeError: expected str, bytes or os.PathLike object, not list"

### ISSUE THREAD

**Issue by dgoekbuget** [vanheeringen-lab/gimmemotifs#148]
Hi,
I get an error using both my own input file as well as the example input file (below) when trying to run `gimme maelstrom test "mm10" output`

Thanks for your help!

```
loc    cluster
chr15:49258903-49259103    NK
chr10:72370313-72370513    NK
chr4:40579259-40579459    Monocytes
chr10:82225678-82225878    T-cells
chr5:134237941-134238141    B-cells
chr5:58858731-58858931    B-cells
chr20:24941608-24941808    NK
chr5:124203116-124203316    NK
chr17:40094476-40094676    Erythroblast
chr17:28659327-28659527    T-cells
```

Std out:

```
2020-10-15 16:10:57,689 - INFO - Starting maelstrom
2020-10-15 16:10:57,722 - INFO - motif scanning (counts)
2020-10-15 16:10:57,725 - INFO - reading table
Traceback (most recent call last):
  File "/home/gd/software/miniconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/commands/maelstrom.py", line 33, in maelstrom
    run_maelstrom(
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/maelstrom.py", line 343, in run_maelstrom
    counts = scan_regionfile_to_table(
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 154, in scan_regionfile_to_table
    np.median([len(seq) for seq in as_fasta(check_regions, genome=genome).seqs])
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/utils.py", line 692, in as_fasta
    return Fasta(fdict=as_seqdict(to_convert, genome, minsize))
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/utils.py", line 614, in _as_seqdict_list
    return _genomepy_convert(to_convert, genome, minsize)
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/utils.py", line 534, in _genomepy_convert
    g.track2fasta(to_convert, tmpfile.name)
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/site-packages/genomepy/genome.py", line 361, in track2fasta
    track_type = self.get_track_type(track)
  File "/home/gd/software/miniconda3/envs/gimme/lib/python3.8/site-packages/genomepy/genome.py", line 334, in get_track_type
    with open(track) as fin:
TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by simonvh** [comment]
Hmm, strange. The command works for me.

```
$ gimme maelstrom test.txt mm10 test.out
2020-10-16 08:42:35,934 - INFO - Starting maelstrom
2020-10-16 08:42:35,948 - INFO - motif scanning (counts)
2020-10-16 08:42:35,949 - INFO - reading table
2020-10-16 08:42:37,955 - INFO - setting threshold
2020-10-16 08:43:05,902 - INFO - creating count table
2020-10-16 08:43:20,027 - INFO - done
```

Can you show the output of `conda list`?

````
conda activate gimme
conda list
```

I'm specifically interested in the version of genomepy, this should be 0.9.0. If it's not, you can install the correct version with `conda install genomepy=0.9.0`.

**Comment by dgoekbuget** [comment]
Thank you Simon for your quick reply.

The genomepy version seems what you expected. See output of conda list below:

(gimme) [gd@go-node-27 gimme-maelstrom]$ conda list

# packages in environment at /home/gd/software/miniconda3/envs/gimme:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
abseil-cpp                20200225.2           he1b5a44_2    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
arrow-cpp                 1.0.1           py38hbfecb28_14_cpu    conda-forge
aws-c-common              0.4.59               he1b5a44_0    conda-forge
aws-c-event-stream        0.1.6                h84e28f3_5    conda-forge
aws-checksums             0.1.9                he252421_2    conda-forge
aws-sdk-cpp               1.8.63               h9b98462_0    conda-forge
bedtools                  2.29.2               hc088bd4_0    bioconda
biopython                 1.78             py38h1e0a361_0    conda-forge
boltons                   20.2.1             pyh9f0ad1d_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.9                he1b5a44_2    conda-forge
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
bucketcache               0.12.1           py38h32f6830_2    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h924ce5b_2    conda-forge
cffi                      1.14.3           py38h1bdcb99_1    conda-forge
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
configparser              5.0.1                      py_0    conda-forge
cryptography              3.1.1            py38hb23e4d4_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
dinamo                    1.0                  h78a066a_0    bioconda
diskcache                 5.0.3              pyh9f0ad1d_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
feather-format            0.4.1              pyh9f0ad1d_0    conda-forge
freetype                  2.10.3               he06d7ca_0    conda-forge
future                    0.18.2           py38h32f6830_2    conda-forge
gadem                     1.3.1                h516909a_2    bioconda
genomepy                  0.9.0                      py_0    bioconda
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
ghostscript               9.18                          1    bioconda
gimmemotifs               0.15.1           py38h0213d0e_0    bioconda
glog                      0.4.0                h49b9bf7_3    conda-forge
grpc-cpp                  1.32.0               h7997a97_1    conda-forge
homer                     4.11            pl526hc9558a2_3    bioconda
htslib                    1.11                 hd3b49d5_0    bioconda
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
kiwisolver                1.2.0            py38hbf85e49_1    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.0                h516909a_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_5    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libprotobuf               3.13.0.1             h8b12597_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libthrift                 0.13.0               h5aa387f_6    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libutf8proc               2.5.0                h516909a_2    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxgboost                1.2.0                he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
llvmlite                  0.34.0           py38h4f45e52_2    conda-forge
logbook                   1.5.3            py38h1e0a361_2    conda-forge
logomaker                 0.8                pyh864c0ab_1    bioconda
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markupsafe                1.1.1            py38h8df0ef7_2    conda-forge
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py38h4d1ce4f_1    conda-forge
meme                      5.1.1           py38pl526hc1f1133_3    bioconda
mpi                       1.0                     openmpi    conda-forge
mysql-connector-c         6.1.11            h876a3cc_1006    conda-forge
ncurses                   6.2                  he1b5a44_2    conda-forge
norns                     0.1.5              pyh864c0ab_1    bioconda
nose                      1.3.7                   py_1006    conda-forge
numba                     0.51.2           py38hc5bc63f_0    conda-forge
numpy                     1.19.2           py38hbc27379_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openjdk                   10.0.2            h14c3975_1015    conda-forge
openmpi                   4.0.5                hdf1f1ad_3    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
orc                       1.6.5                hd3605a7_0    conda-forge
pandas                    1.1.3            py38hc5bc63f_2    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
pathlib                   1.0.1            py38h32f6830_3    conda-forge
patsy                     0.5.1                      py_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-algorithm-cluster    1.58            pl526h14c3975_0    bioconda
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-cgi                  4.44            pl526h14c3975_1    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-dbi                  1.642                   pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-file-which           1.23                    pl526_0    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-template        2.97                    pl526_1    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-log-log4perl         1.49                    pl526_0    bioconda
perl-math-cdf             0.1             pl526h14c3975_5    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44            pl526h4e0c4b3_7    bioconda
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pillow                    8.0.0            py38h9776b28_0    conda-forge
pip                       20.2.3                     py_0    conda-forge
prosampler                1.0                  hc9558a2_0    bioconda
psutil                    5.7.2            py38h8df0ef7_1    conda-forge
py-xgboost                1.2.0            py38h32f6830_0    conda-forge
pyarrow                   1.0.1           py38h9235441_14_cpu    conda-forge
pybedtools                0.8.1            py38h1c8e9b9_2    bioconda
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyfaidx                   0.5.9.1            pyh864c0ab_1    bioconda
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py38hbdc2ae9_1    bioconda
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-xxhash             2.0.0            py38h1e0a361_1    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
qnorm                     0.5.1              pyh9f0ad1d_0    conda-forge
re2                       2020.10.01           he1b5a44_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
represent                 1.5.1                      py_2    bioconda
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
scikit-learn              0.23.2           py38hee58b96_0    conda-forge
scipy                     1.5.2            py38h8c5af15_1    conda-forge
seaborn                   0.11.0                        0    conda-forge
seaborn-base              0.11.0                     py_0    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
statsmodels               0.12.0           py38hab2c0dc_1    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tornado                   6.0.4            py38h1e0a361_2    conda-forge
tqdm                      4.50.2             pyh9f0ad1d_0    conda-forge
trawler                   2.0                           3    bioconda
ucsc-bedtogenepred        377                  h446ed27_1    bioconda
ucsc-bigbedtobed          377                  h446ed27_1    bioconda
ucsc-genepredtobed        377                  h446ed27_3    bioconda
ucsc-genepredtogtf        377                  h446ed27_3    bioconda
ucsc-gff3togenepred       377                  h446ed27_1    bioconda
ucsc-gtftogenepred        377                  h446ed27_3    bioconda
unzip                     6.0                  h516909a_2    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
weeder                    2.0                  hc9558a2_4    bioconda
wget                      1.20.1               h22169c7_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xdg                       4.0.1                      py_1    conda-forge
xgboost                   1.2.0            py38h950e882_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xxhash                    0.8.0                h516909a_1    conda-forge
xxmotif                   1.6                  h2d50403_2    bioconda
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Comment by simonvh** [comment]
I think I may have found the problem. Is your input file space-separated instead of tab-separated?

**Comment by dgoekbuget** [comment]
Great point! It worked!

Have good rest of your day!

**Comment by simonvh** [comment]
Great! We'll add a more informative error for the next release.
