### ISSUE TITLE
gimme maelstrom aggregation

### ISSUE THREAD

**Issue by fgualdr** [vanheeringen-lab/gimmemotifs#149]
Hi,

I am trying to run gimme maelstrom from command line.
From the code and description in principle is possible to specify the type of aggregation of the score.
How can I specify it from command line when submitting gimme from a bash script?

Thanks
Francesco

**Comment by simonvh** [comment]
This should be the option you mean:

```
  -a method, --aggregation method
                        How to combine motifs from individual methods. Default is "int_stouffer", for
                        inverse normal transform of ranks, followed by Stouffer's method to combine
                        z-scores. Alternatively, specify "stuart" for log-transformed rank aggregation
                        p-values.

```
