### ISSUE TITLE
Browser depedent motif % sort

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/gimmemotifs#151]
**Describe the bug**
The % containing motif sort in the browser is probably on string and not on number.
E.g. the 25% GATA motif from this dataset:
http://ocimum.science.ru.nl/tmp/danRer11/gimme.vertebrate.v5.0.pfm/10000/20/gimme.maelstrom.report.html
is sorted to the bottum in Internet explorer and google chrome,
while firefox sorts it above the 2% motifs and below the 3% motifs.

It also breaks at the 1 and >1%

**To Reproduce**
Look at the http://ocimum.science.ru.nl/tmp/danRer11/gimme.vertebrate.v5.0.pfm/10000/20/gimme.maelstrom.report.html

**Expected behavior**
Sort based on floats and not strings?

**Comment by simonvh** [comment]
@JGASmits is this still the case with version 0.15.1?

**Comment by Maarten-vd-Sande** [comment]
I believe it was run with gimme 0.15.1

**Comment by Maarten-vd-Sande** [comment]
Is the version number somewhere in the html or folder?

**Comment by simonvh** [comment]
Version should be in some of the output files. I think in `final.out.txt`, or at least in the `activity*txt` files or the `motif.score.txt`.

**Comment by Maarten-vd-Sande** [comment]
Version 0.15.0, I'll try with 0.15.1

**Comment by simonvh** [comment]
Ah never mind. The sorting fixes should be present in 0.15.0.

This is some Javascript hacking in https://github.com/vanheeringen-lab/gimmemotifs/blob/b9ae91de4307d200c6633527b7de8e8254a11ef3/data/templates/sortable/sortable.min.js#L2

If you have an idea how to fix it @Maarten-vd-Sande I'd be happy!

**Comment by Maarten-vd-Sande** [comment]
No, I have extremely minimal javascript experience (not sure what happens in that big line). 

My first guess would be that it is sorted alphabetically and not numerically. You are mixing numbers and "non-numbers" (<1), so it might be that it all gets casted to strings?

**Comment by simonvh** [comment]
The non-number characters are removed before the number is parsed. However, apparently this doesn't work flawlessly.

**Comment by Maarten-vd-Sande** [comment]
Plus the behaviour is different between chrome (Jos), and firefox (me)... So it might be something else? For Chrome it works fine I think

**Comment by JGASmits** [comment]
No for chrome it also breaks down when there are two digit numbers being sorted. I think I saw the same problem in my newest 0.15.1 maelstrom analysis. No clue how java works though.

**Comment by Maarten-vd-Sande** [comment]
Potentially related to this?
https://forum.freecodecamp.org/t/the-sort-method-behaves-different-on-different-browsers/237221
and
https://stackoverflow.com/a/5002924/9544516

Not entirely sure where the comparisons are being made, but I think it is this:
```
l.sort(c),u=0,y=l.length;y>u;u++
```

Maybe changing it into `y-u` improves it?

**Comment by simonvh** [comment]
This is the relevant parsing regex:

```
d=/^(-?[£$¤]?[\d,.e\-]+%?|inf)$/
```

**Comment by Maarten-vd-Sande** [comment]
When I inject the new regex it indeed works for me on Firefox! @JGASmits can you confirm that this works for you?

http://ocimum.science.ru.nl/tmp/danRer11/gimme.vertebrate.v5.0.pfm/10000/20/gimme.maelstrom.report.html

**Comment by JGASmits** [comment]
It works propperly for all except the 1 and <1! 👍
