### ISSUE TITLE
gimme motif error after updating conda

### ISSUE THREAD

**Issue by dimurali93** [vanheeringen-lab/gimmemotifs#153]
Hi, i was running gimme motifs a while ago and suddenly it starting giving me the following error. could u please help me with this?
File "/home/dimurali/miniconda3/envs/gimme/bin/gimme", line 8, in <module>
    from gimmemotifs.cli import cli
  File "/home/dimurali/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/__init__.py", line 61, in <module>
    from . import denovo      # noqa: F401
  File "/home/dimurali/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/denovo.py", line 52, in <module>
    from gimmemotifs.report import create_denovo_motif_report
  File "/home/dimurali/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/report.py", line 63, in <module>
    class ExtraStyler(Styler):
  File "/home/dimurali/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/report.py", line 72, in ExtraStyler
    template = env.get_template("table.tpl")
  File "/home/dimurali/miniconda3/envs/gimme/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/dimurali/miniconda3/envs/gimme/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/dimurali/miniconda3/envs/gimme/lib/python3.8/site-packages/jinja2/loaders.py", line 429, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: table.tpl

**Comment by simonvh** [comment]
Hmm, this indeed has to do with the update of GimmeMotifs. Can you try to re-create the environment?

```
conda env remove --name gimme
conda create -n gimme gimmemotifs=0.15.1
```

**Comment by dimurali93** [comment]
I am still getting this error after following the following steps mentioned
above .

Traceback (most recent call last):

  File "/home/dimurali/anaconda3/envs/gimme/bin/gimme", line 8, in <module>

    from gimmemotifs.cli import cli

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/__init__.py",
line 61, in <module>

    from . import denovo      # noqa: F401

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/denovo.py",
line 52, in <module>

    from gimmemotifs.report import create_denovo_motif_report

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/report.py",
line 63, in <module>

    class ExtraStyler(Styler):

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/report.py",
line 72, in ExtraStyler

    template = env.get_template("table.tpl")

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/jinja2/environment.py",
line 883, in get_template

    return self._load_template(name, self.make_globals(globals))

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/jinja2/environment.py",
line 857, in _load_template

    template = self.loader.load(self, name, globals)

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/jinja2/loaders.py",
line 429, in load

    raise TemplateNotFound(name)

jinja2.exceptions.TemplateNotFound: table.tpl


Also when i try to install the current version of the genome i get the
following error :

File "/home/dimurali/anaconda3/envs/gimme/bin/genomepy", line 10, in
<module>

    sys.exit(cli())

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/click/core.py",
line 829, in __call__

    return self.main(*args, **kwargs)

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/click/core.py",
line 782, in main

    rv = self.invoke(ctx)

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/click/core.py",
line 1259, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/click/core.py",
line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/click/core.py",
line 610, in invoke

    return callback(*args, **kwargs)

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/genomepy/cli.py",
line 221, in install

    genomepy.install_genome(

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/genomepy/functions.py",
line 305, in install_genome

    p.download_genome(

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/genomepy/provider.py",
line 235, in download_genome

    mkdir_p(out_dir)

  File
"/home/dimurali/anaconda3/envs/gimme/lib/python3.8/site-packages/genomepy/utils.py",
line 177, in mkdir_p

    os.makedirs(path, exist_ok=True)

  File "/home/dimurali/anaconda3/envs/gimme/lib/python3.8/os.py", line 213,
in makedirs

    makedirs(head, exist_ok=exist_ok)

  File "/home/dimurali/anaconda3/envs/gimme/lib/python3.8/os.py", line 213,
in makedirs

    makedirs(head, exist_ok=exist_ok)

  File "/home/dimurali/anaconda3/envs/gimme/lib/python3.8/os.py", line 223,
in makedirs

    mkdir(name, mode)

PermissionError: [Errno 13] Permission denied: '/data'


Divya Murali
Graduate student
University of California, San Diego

**Comment by simonvh** [comment]
Hi Divya. I think you get this error when installing a genome via genomepy? Do you have permission to write in the the directory `/data` ?

**Comment by simonvh** [comment]
@dimurali93 I'm assuming this issue is fixed. Feel free to close if it still occurs.
