### ISSUE TITLE
meaning of this error ?

### ISSUE THREAD

**Issue by dimurali93** [vanheeringen-lab/gimmemotifs#154]
HI all, 
while running gimme-motifs, i am getting the following error . could you help me understand this ?
/home/dimurali/anaconda3/envs/gimme/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)

**Comment by simonvh** [comment]
This is a warning coming from a pybedtools function related to change in Python 3.8. It should be fixed with a new release of pybedtools. For now you can safely ignore it.
