### ISSUE TITLE
configuration deleted while running multiple gimme jobs on cluster

### ISSUE THREAD

**Issue by fgualdr** [vanheeringen-lab/gimmemotifs#155]
Hi,

I am running gimme on a cluster sending different jobs in parallel.
To solve the cache issue I am using the trick of creating a temporary cache:

TMPDIR=/tmp_dmso/
NEW_CACHE=$TMPDIR/cache
mkdir -p $NEW_CACHE
if [ -z $XDG_CACHE_HOME ]; then
    XDG_CACHE_HOME=$HOME/.cache
fi
cp -r $XDG_CACHE_HOME/gimmemotifs $NEW_CACHE/
export XDG_CACHE_HOME=$NEW_CACHE

All is fine unless when I run multiple jobs in parallel and the gimmeconfig gets delegated.
Is there a way to specify the config file for each run?
So that gimme does not re-create it each time?

**Comment by simonvh** [comment]
I think you should be able to do the same trick with `$XDG_CONFIG_HOME` and copying `~/.config/gimmemotifs` to that directory. Haven't tested it though. 

I'm aware that running gimmemotifs in parallel is not ideal at the moment. We're looking for ways around that, hopefully for a new release.
