### ISSUE TITLE
ValueError interrrupting gimme motifs command

### ISSUE THREAD

**Issue by sufyazi** [vanheeringen-lab/gimmemotifs#156]
**Describe the bug**
So I have been running `gimme motifs` recently (new user), and today I stumbled upon this one error that keeps popping up that I could not trace why. I have two different sets of peaks, in the form of narrowPeak files, and they are a subset of peaks from the original narrowPeak files spit out by MACS2. These two narrowPeak files are replicated peaks (but not tightly concordant, so the regions are not exactly the same). Oddly, I successfully run `gimme motifs` on one narrowPeak file (replicate 1), while the program spits out a Value Error when run with another narrowPeak file (replicate 3). They are similarly formatted files and I have checked to see if there are any weird lines that is messing up the script, but to no avail.

**To Reproduce**
Here's the line I run for `gimme motifs`:
```
gimme motifs bdp2-macs2-rep1_peaks_filtered_rifin_only.narrowPeak gimme.BDP2.rifins.upstream.rep1.test -g /Users/sufyazi/Bioinformatics/PhD_works/BDP2_project/genome_db/PlasmoDB-34_Pfalciparum3D7_Genome.fasta -f 0.7
```

**Expected behavior**
When I run this command, I got these lines

```
2020-12-03 00:06:40,619 - INFO - creating background (matched GC%)
/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
2020-12-03 00:06:43,476 - INFO - starting full motif analysis
2020-12-03 00:06:43,476 - INFO - using size of 200, set size to 0 to use original region size
2020-12-03 00:06:43,477 - INFO - preparing input from BED
2020-12-03 00:06:44,442 - INFO - starting motif prediction (xl)
2020-12-03 00:06:44,442 - INFO - tools: MEME, BioProspector, Homer
2020-12-03 00:06:44,873 - INFO - all jobs submitted
```
And the run will run rather smoothly (there will be an annoying 'KeyParam' errors popping up but these does not halt the execution of the command and I could get output files when the run completed itself).

**Error logs**
The issue here is, when I run the same command, but with another narrowPeak file:
```
gimme motifs bdp2-macs2-rep3_peaks_filtered_rifin_only.narrowPeak gimme.BDP2.rifins.upstream.rep3.test -g /Users/sufyazi/Bioinformatics/PhD_works/BDP2_project/genome_db/PlasmoDB-34_Pfalciparum3D7_Genome.fasta -f 0.7
```
I get this weird error
```
2020-12-03 00:04:55,534 - INFO - creating background (matched GC%)
/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
Traceback (most recent call last):
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/commands/motifs.py", line 87, in motifs
    create_background_file(
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/background.py", line 120, in create_background_file
    m = MatchedGcFasta(inputfile, genome, number=number, size=size)
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/background.py", line 564, in __init__
    matched_gc_bedfile(tmpbed, matchfile, genome, number, size=size)
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/background.py", line 538, in matched_gc_bedfile
    df.loc[df["bin"] == b, ["chrom", "start", "end"]].sample(n).to_csv(
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/pandas/core/generic.py", line 4993, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 902, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken
```
I have double checked the input narrowPeak files and compared the problematic ones with the working one and there's nothing different structurally that may disrupt the command. I am not sure how to proceed from here. They even have around the same number of peak lines (~150-160 lines) in each file (expected, as they are replicated dataset and a subset of regions associated with a set of genes I'm interested in). 

I hope someone can help me. I provided a ZIP folder with all of the input files I used for the command described above if you would like to try to replicate the error. [gimmemotifs-sufyazi.zip](https://github.com/vanheeringen-lab/gimmemotifs/files/5629561/gimmemotifs-sufyazi.zip)

**Installation information (please complete the following information):**
 - OS: I am using Macbook Pro MacOS to run the analysis.
 - Installation and version: conda package (pypi) gimmemotifs 0.15.1+2.gf3d08fa (I saw you proposed a hotfix for a valueError in one of the issue threads so I tried it but it didn't change anything for me)

**Additional context**
Since the day I installed gimme, whenever I run gimme motifs command even if the run is successful (and I can get output files), my computer would seem to be stuck at trying to resolve KeyParam error (seem to be stuck in a loop) and I usually need to ctrl+C as soon as I see the `run is finished` to manually terminate the command. I could make a separate thread if you want me to report this error.

**Comment by simonvh** [comment]
Hi @sufyazi , I'll have a look! For the KeyParam error that you mention, please make a different issue as you suggest. This error is completely new to me and I'd like to have a look to see if we can fix that.

**Comment by simonvh** [comment]
As it turns out, you found a bug that I never noticed before. As the Plasmodium doesn't have GC-rich sequences it is impossible to retrieve a random sequence from the genome with GC% >= 80%!
It should be fixed in the current `develop` branch, you can try it out by installing this in your conda environment:

```
 pip install git+https://github.com/vanheeringen-lab/gimmemotifs.git@2d3b70b
```

**Comment by sufyazi** [comment]
Oh thank you for the quick response! That is interesting to say the least, but for some reason I couldn't install the fix - it errored out at the end for me. This is the last line of error if this helps? 

```
ERROR: Command errored out with exit status 1: /Users/sufyazi/opt/anaconda3/envs/gimme/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3b/5qbsylps7g11tqh0b1h0w4d00000gn/T/pip-install-xczi9b0y/pybigwig/setup.py'"'"'; __file__='"'"'/private/var/folders/3b/5qbsylps7g11tqh0b1h0w4d00000gn/T/pip-install-xczi9b0y/pybigwig/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3b/5qbsylps7g11tqh0b1h0w4d00000gn/T/pip-record-pcyc0br9/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sufyazi/opt/anaconda3/envs/gimme/include/python3.8/pyBigWig Check the logs for full command output.
```

Not sure what went wrong. Can you advise? P.S. I will make a separate comment for the KeyParam error next time I see it.

**Comment by simonvh** [comment]
Hopefully this should fix that install error:

```
conda activate gimme
conda install biofluff=3.0.4
pip install git+https://github.com/vanheeringen-lab/gimmemotifs.git@2d3b70b
```

**Comment by sufyazi** [comment]
Hi @simonvh the issue is resolved now! Thank you! The keyError 'params' still persists though although the run finished without issues so I'll be making a separate thread for that. Feel free to close this issue!
