### ISSUE TITLE
Motif to TF mapping nonredundant.motifs.pfm file

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/gimmemotifs#161]
When running gimme maelstrom using a 'nonredundant.motifs.pfm' file generated by a different maelstrom run (on different yet similar data), the mapping rate of motifs to TF drastically drops. 

Image of an original run: 
![image](https://user-images.githubusercontent.com/47240368/102053989-f827d880-3de8-11eb-8b1e-883c292e7a7e.png)

Image of a run on similarish data using the nonredundant.motifs.pfm file from the previous analysis:

![image](https://user-images.githubusercontent.com/47240368/102054140-33c2a280-3de9-11eb-8d04-9a1e664e8254.png)

**Comment by JGASmits** [comment]
On first glance, the problem seems to be the motifs are not pressent in  'nonredundant.motifs.motif2factors.txt',
however they are still present in "nonredundant.motifs.pfm". Which is interesting.

**Comment by JGASmits** [comment]
Link to example files: 
/ceph/....etc..../jsmits/Epi_fate_specifiers/analysis/Python_version_2020-11-12/maelstrom_results/maelstrom_H3K27ac_all/nonredundant.motifs.pfm
/ceph/....etc..../jsmits/Epi_fate_specifiers/analysis/Python_version_2020-11-12/maelstrom_results/maelstrom_H3K27ac_all/nonredundant.motifs.motif2factors.txt

**Comment by simonvh** [comment]
It seems the pfm file actually contains all motifs, not only the non-redundant ones! That should be straightforward to fix.
