### ISSUE TITLE
wrong percent of occurence

### ISSUE THREAD

**Issue by irzhegalova** [vanheeringen-lab/gimmemotifs#162]
Hey!
I find out that the procedure for counting percent of motif occurrence does not take into account that in one peak it is possible to have more than one motif occurrence. In that case we should probably count number of peaks with at least 1 occurrence, shouldn't we?
https://github.com/vanheeringen-lab/gimmemotifs/blob/50abbc2e3ab86770b2ac53b1adc94c6a533d11ec/gimmemotifs/maelstrom.py#L512

**Comment by simonvh** [comment]
You are completely correct! thanks for reporting
