### ISSUE TITLE
pyfaidx.fetchError when running gimme motifs

### ISSUE THREAD

**Issue by ymquint** [vanheeringen-lab/gimmemotifs#165]
**Describe the bug**
I want to use  .narrowPeak files generated by seq2science as input for gimme motifs (six files in total). However, for two out of the six files  gimme motifs returns an error: pyfaidx.fetchError: requested start coordinate must be 1.  

**To Reproduce**
For all files I run a standard gimme motifs command (separately) 
`gimme motifs INPUT.narrowPeak OUTPUTPATH  -g GENOMEPATH ` 

**Expected behavior**
Because the other  .narrowPeak files run fine, I would expect gimme motifs to also have no problems with the current two. 

**Error logs**
![image](https://user-images.githubusercontent.com/76217186/103550439-2e68ed00-4ea9-11eb-8d9a-11e4f7674196.png)

**Installation information:**
 - OS: [Linux]
 - Installation [conda]
 - Version [0.15.2]

**Comment by simonvh** [comment]
Hey @ymquint, I suspect it's related to this line:
```
chrUn_GL456393  72      276     /scratch/bacint/yquint/atac-seq_second_try/macs2/mm10-CV_ENR_day9_peaks.temp.narrowPeak_narrowPeak27775      192     .       0       0       0       134
```
Can you try to see what happens if your remove this line?

(It's still a bug in GimmeMotifs, but changing the file is quicker than waiting for a fixed version.)

**Comment by ymquint** [comment]
Hi @simonvh , when removing the line it works perfect. Thank you!
