### ISSUE TITLE
Gimme motifs not using -f (fraction) provided

### ISSUE THREAD

**Issue by adeben1** [vanheeringen-lab/gimmemotifs#166]
**Describe the bug**
Gimme motifs is not apparently using the -f value provided.
 
**To Reproduce**
 I've run gimme motifs commnad providing input, background and genome in fasta format with the -s flag set to 0 as well as -f set to 0.5. Here is one example. 
`gimme motifs diff_peaks_down_MB.bed.fa down_MB_nocenteredx2_b_f0,5 -g ../../genome/Nfu_20150522.softmasked_genome.fa -b ../nucfree/allPeaks_MB.bed.fa -s 0 -f 0.5` 

**Expected behavior**
In the file params.txt, the fraction should indicate 0.5, however it appears the default 0.2. 

**Error logs**
I copy the content of the file params.txt.

fraction	0.2
use_strand	False
abs_max	1000
analysis	xl
enrichment	1.5
size	0
lsize	500
background	['custom']
cluster_threshold	0.95
scan_cutoff	0.9
available_tools	MDmodule,MEME,MEMEW,DREME,Weeder,GADEM,MotifSampler,Trawler,Improbizer,BioProspector,Posmo,ChIPMunk,AMD,HMS,Homer,XXmotif,ProSampler,DiNAMO
tools	MEME,Homer,BioProspector
pvalue	0.001
max_time	-1.0
ncpus	12
motif_db	gimme.vertebrate.v5.0.pfm
use_cache	False
custom_background	../nucfree/allPeaks_MB.bed.fa
genome	../../genome/Nfu_20150522.softmasked_genome.fa

In addition, the .log file says it is using 0.2 as a fraction. From gimmemotifs.log:
`2021-01-13 09:32:15,478 - gimme.config - DEBUG -   fraction: 0.2`

**Installation information (please complete the following information):**
 - OS: Linux
 - Installation conda
 - Version v0.14.4

**Comment by simonvh** [comment]
I'll have a look, thanks for reporting!

**Comment by kirbyziegler** [comment]
Easy fix here: 

https://github.com/vanheeringen-lab/gimmemotifs/issues/177
