### ISSUE TITLE
Run Gimme motif on pre-computed score tables

### ISSUE THREAD

**Issue by fgualdr** [vanheeringen-lab/gimmemotifs#171]
Hi,

I would like to know if there is an in built function that allows to compute motif enrichment starting from score_tables for target and background directly.

I need to check enrichments in subset of the same list of sequences and would like to speed up processing by simply partition the same target score_table and feed this into the motif enrichment tool.

Maybe can be done directly in python but don't know how.

Cheers,

Francesco

**Comment by simonvh** [comment]
Hmmm not really a user-friendly way.
You can use `calc_stats_iterator` from `gimmemotifs.stats`:

```
for motif_stats in calc_stats_iterator(
        motifs=pfmfile,
        fg_table=score_table,
        bg_table=bg_score_table,
    ):
    # your code here
```

You would have to do some processing on the stats to get them nicely formatted etc. See https://github.com/vanheeringen-lab/gimmemotifs/blob/50abbc2e3ab86770b2ac53b1adc94c6a533d11ec/gimmemotifs/commands/motifs.py#L199-L229.
But I'm afraid this is not nicely modular right now.
