### ISSUE TITLE
Rename ouput coverage table

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/gimmemotifs#173]
**Is your feature request related to a problem? Please describe.**
Right now the ID column (chr1:1023-212)0 that is outputed by coverage table is called: "loc"
However this is very inconvenient when using it in python (where you cant call the column via df.loc  for obvious reasons).

**Describe the solution you'd like**
If the column instead would be called something more descriptive e.g. 'region' I think that would be more descriptive and easier to use. :)

**Comment by simonvh** [comment]
@JGASmits I just tried to fix this, but I can't find any reference to `loc` in the code. Is this with GimmeMotifs version 15.2? I'm now completely confused as to where this comes from...

**Comment by JGASmits** [comment]
oef, it turned out to be a problem from my side! "Old" code I didnt check. I should have been more vigilant before starting the sisue. 

The only location where 'loc' is actually is vissible is in the documentation regarding maelstrom input file format examples. Which I think is what threw me of when i wrote this code a long time ago. 

My appologies!
