### ISSUE TITLE
gimmemotifs lacks module pyarrow when installed with pip

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/gimmemotifs#176]
**Describe the bug**
see title

**Expected behavior**
Dask also has extra dependencies when installing over Pip. Easiest solution would be to document it in [the same way.](https://docs.dask.org/en/latest/install.html#pip)

**Error logs**
[github action log](https://github.com/vanheeringen-lab/ANANSE/pull/31/checks?check_run_id=1905454221)

**Installation information (please complete the following information):**
 - OS: Linux
 - Installation: pip
 - Version: latest

**Comment by rsvasan** [comment]
Gimmemotifs version 0.15.3 installed via pip in Ubuntu 20.04 (pip install gimmemotifs==0.15.3), is missing the "pyarrow" module. See the error below:
Traceback (most recent call last):
  File "/home/srini/gmotifs/gimme/bin/gimme", line 8, in <module>
    from gimmemotifs.cli import cli
  File "/home/srini/gmotifs/gimme/lib/python3.8/site-packages/gimmemotifs/__init__.py", line 58, in <module>
    from . import background  # noqa: F401
  File "/home/srini/gmotifs/gimme/lib/python3.8/site-packages/gimmemotifs/background.py", line 29, in <module>
    from pyarrow.lib import ArrowInvalid
ModuleNotFoundError: No module named 'pyarrow'
