### ISSUE TITLE
FIX: XXMotif.py does not parse motif results

### ISSUE THREAD

**Issue by kirbyziegler** [vanheeringen-lab/gimmemotifs#178]
### Running: test_tools.py

**[XXMotif.py]**: line 93: `motifs, stdout, stderr = self._read_and_label_motifs(outfile, stdout, stderr, fmt="xxmotif")`
**[motifprogram.py]**: line 41: `motifs = read_motifs(outfile, fmt="meme")`
**[motif.py]**: line 1591: `def read_motifs(infile=None, fmt="pfm", as_dict=False):`
**[motif.py]**: line 1621: `motifs = _read_motifs_from_filehandle(f, fmt)`

- The **fmt** variable is being overwritten from "xxmotif" to "meme" by _motifprogram.py_ (line 41)

### Solution:
**[motifprogram.py]**: line 41: `motifs = read_motifs(outfile, fmt)`

**Comment by simonvh** [comment]
Good call!
