### ISSUE TITLE
FIX: yamda.py: attempts to run python script without python command 

### ISSUE THREAD

**Issue by kirbyziegler** [vanheeringen-lab/gimmemotifs#180]
### Solution:
**yamda.py:**

line 71: 

     cmd = "python %s -i %s -j %s -n %s -w %s -oc %s  %s" % (
            bin,
            fastafile,
            params["background"],
            params["number"],
            params["width"],
            self.tmpdir,
            params["strand"],
        )

- **python** _run_em.py_ [yamda_parameters]

**Comment by simonvh** [comment]
Ah! Yeah I added YAMDA support but have never really thoroughly tested it. I guess I had made the `run_em.py` script executable on my side.
