### ISSUE TITLE
Interpreting maelstrom final.out.txt

### ISSUE THREAD

**Issue by adeben1** [vanheeringen-lab/gimmemotifs#182]
I'd like to perform downstream analysis with the output from gimme maelstrom, so I'd like to know if all motifs from final.out.txt are interesting or maybe filtering by aggregated z-score would be a good starting point.

**Comment by simonvh** [comment]
Hi @adeben1, the `final.out.txt` contains all, unfiltered motifs. These are definitely not all interesting! Yes, I would recommend filtering by z-score, this is indeed what is also being done for the HTML report.
