### ISSUE TITLE
CLIP-seq analysis - RNA motifs

### ISSUE THREAD

**Issue by adomingues** [vanheeringen-lab/gimmemotifs#184]
Hi,

Is it possible to use `gimmemotifs` for the detection of RNA motifs from CLIP-seq derived locations? Off the top of my head, the main differences from ChIP-seq (DNA) motifs is that RNA motifs will be on a single strand, that to which the RNA-binding protein binds to, rather than both strands. With that in mind I have called binding site with a CLIP-seq specific tool, extracted the DNA sequencing from the binding strand, and used this command for motif discovery:

```
gimme motifs pred.rat.top1000.fa ./ -g ${GENOME}/Sequence/WholeGenomeFasta/genome.fa -N 10 --denovo --size 50 --analysis small --singlestrand
```

I am assuming that using `--singlestrand` only the sequences in the file will be use for motif prediction, and not those from both strands. Is this correct? `--size 50 --analysis small` are being used because there is a published motif for this particular protein and it is small - my goal is to partly recover the published motif from my data. 

Am I missing nay other setting or doing this entirily the wrong way? 

Cheers.

**Comment by simonvh** [comment]
Hi @adomingues 

First, I have to say that I have never used gimme motifs in the way, nor am I familiar with others that have used it. That being said, it should work? Your assumptions are correct. The `--singlestrand` argument will make sure that the *de novo* motif prediction is only performed on the input sequence, not on the reverse complement. However, not all *de novo* motif tools support this, so it may vary.

**Comment by adomingues** [comment]
Thanks a lot for the input @simonvh.

> However, not all de novo motif tools support this, so it may vary.

I will keep this in mind when looking at the results.
