### ISSUE TITLE
how to find the location of motif

### ISSUE THREAD

**Issue by BenxiaHu** [vanheeringen-lab/gimmemotifs#186]
hello,
    I have run `gimme maelstrom` to predict motifs based on ATAC-seq peaks from multiple groups. Now I want to know whether a specific peak contain a motif. here are the results I got:
![image](https://user-images.githubusercontent.com/12387462/115048538-aaf76880-9ea7-11eb-9796-0000e7be0aa0.png)

**Comment by simonvh** [comment]
Hi, the motif scan result are in `motif.count.txt.gz`. This is a gzipped file that contains a table with peaks (rows) and motifs (columns). These are motif counts, based on a 1% FPR threshold.

**Comment by biohubx** [comment]
thanks.
I just checked the motif.count.txt.gz file, and found that the number of loci in motif.count.txt.gz file (43647) is lesser than that of input file (106745). for example, I want to check whether this locus (chr21:26140076-26140621) has contained any motifs, but motif.count.txt.gz file does not contain this locus. it looks weird
