### ISSUE TITLE
scanner.set_background "OperationalError: attempt to write a readonly database"

### ISSUE THREAD

**Issue by celinesin** [vanheeringen-lab/gimmemotifs#188]
**Describe the bug**
I am using gimmemotifs in a jupyter notebook installed in a docker container.  When trying to "set_background", I get "OperationalError: attempt to write a readonly database"

I think I probably need to chmod a specific file or directory, but I'm not sure which one.

**To Reproduce**
```
from gimmemotifs.scanner import Scanner
s = Scanner()
s.set_background(genome='hg19', size=200)
```

**Expected behavior**
not sure, but hopefully no error!

**Error logs**
```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-13-d39db170f527> in <module>
      1 from gimmemotifs.scanner import Scanner
      2 s = Scanner()
----> 3 s.set_background(genome='hg19', size=200)

/opt/conda/lib/python3.8/site-packages/gimmemotifs/scanner.py in set_background(self, fname, genome, size, nseq, gc, gc_bins)
    725         logger.debug("using background: genome {} with size {}".format(genome, size))
    726         lock.acquire()
--> 727         with Cache(CACHE_DIR) as cache:
    728             self.background_hash = "d{}:{}:{}:{}".format(
    729                 genome, int(size), gc, str(gc_bins)

/opt/conda/lib/python3.8/site-packages/diskcache/core.py in __init__(self, directory, timeout, disk, **settings)
    479         for key, value in sorted(sets.items()):
    480             if key.startswith('sqlite_'):
--> 481                 self.reset(key, value, update=False)
    482 
    483         sql(

/opt/conda/lib/python3.8/site-packages/diskcache/core.py in reset(self, key, value, update)
   2443                 try:
   2444                     try:
-> 2445                         ((old_value,),) = sql(
   2446                             'PRAGMA %s' % (pragma)
   2447                         ).fetchall()

OperationalError: attempt to write a readonly database
```

**Installation information (please complete the following information):**
 - Ubuntu 20.04.1
 - conda install gimmemotifs==0.14.4

**Comment by simonvh** [comment]
Hmm, this when caching, this means that `~/.cache/gimmemotifs/` is used. Could be related to running it in a Docker. We don't do that ourselves so don't have a lot of experience with Docker-related issues. Maybe the following would help:

```
mkdir /home/simon/gimmemotifs
```

and then add something like the following to your docker command:

`-v /home/simon/gimmemotifs:/root/ `

This would mean that all temporary, cache and index files from gimmemotifs (and genomepy, which is used by gimme), will be stored in `/home/simon/gimmemotifs` (in this example) and will also be saved for when the (read-only) docker instance terminates.

**Comment by celinesin** [comment]
Thanks for the hint!  I solved it by adding

RUN chmod 777 ~/.cache/gimmemotifs/

to my docker file.
