### ISSUE TITLE
Error while running tutorial

### ISSUE THREAD

**Issue by fneuh** [vanheeringen-lab/gimmemotifs#189]
**Describe the bug**
I was following the tutorial (https://gimmemotifs.readthedocs.io/en/master/tutorials.html#find-de-novo-motifs). When searching for de-novo motifs I get the following error:

$ gimme motifs Gm12878.CTCF.top500.narrowPeak gimme.CTCF -g hg19 --denovo
2021-05-25 09:59:02,874 - INFO - creating background (matched GC%)
Traceback (most recent call last):
  File "/home/neuhaus/miniconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/commands/motifs.py", line 87, in motifs
    create_background_file(
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/background.py", line 121, in create_background_file
    m = MatchedGcFasta(inputfile, genome, number=number, size=size)
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/background.py", line 577, in __init__
    matched_gc_bedfile(tmpbed, matchfile, genome, number, size=size)
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/background.py", line 510, in matched_gc_bedfile
    fraction = number / len(gc)
ZeroDivisionError: division by zero

$ tree gimme.CTCF/
gimme.CTCF/
├── input.w200.bed
└── motif_scan_results

The input.w200.bed looks alright, it contains 500 lines. 
$ head -n 5 gimme.CTCF/input.w200.bed
chr11   190037  190237  1501.49835704239
chr14   106873577       106873777       1275.01449536283
chr14   106765204       106765404       1264.07667497398
chr15   22461178        22461378        1111.26912053378
chr14   107119996       107120196       996.90008265053

**To Reproduce**
I pretty much followed the tutorial step-by-step, but for completness here are the commands:

$ conda create -n gimme python=3 gimmemotifs
...
Executing transaction: \
For Linux 64, Open MPI is built with CUDA awareness but this support is disabled by default.
To enable it, please set the environment variable OMPI_MCA_opal_cuda_support=true before
launching your MPI processes. Equivalently, you can set the MCA parameter in the command line:
mpiexec --mca opal_cuda_support 1 ...

In addition, the UCX support is also built but disabled by default.
To enable it, first install UCX (conda install -c conda-forge ucx). Then, set the environment
variables OMPI_MCA_pml="ucx" OMPI_MCA_osc="ucx" before launching your MPI processes.
Equivalently, you can set the MCA parameters in the command line:
mpiexec --mca pml ucx --mca osc ucx ...
Note that you might also need to set UCX_MEMTYPE_CACHE=n for CUDA awareness via UCX.
Please consult UCX's documentation for detail.
...
done

$ conda activate gimme
$ conda env config vars set OMPI_MCA_opal_cuda_support=true
$ conda install -c conda-forge ucx
$ conda env config vars set OMPI_MCA_pml="ucx"
$ conda env config vars set OMPI_MCA_osc="ucx"
$ conda deactivate; conda activate gimme; conda env config vars list
OMPI_MCA_opal_cuda_support = true
OMPI_MCA_pml = ucx
OMPI_MCA_osc = ucx

$  wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/integration_data_jan2011/byDataType/peaks/jan2011/spp/optimal/hub/spp.optimal.wgEncodeBroadHistoneGm12878CtcfStdAlnRep0_VS_wgEncodeBroadHistoneGm12878ControlStdAlnRep0.bb
$ bigBedToBed spp.optimal.wgEncodeBroadHistoneGm12878CtcfStdAlnRep0_VS_wgEncodeBroadHistoneGm12878ControlStdAlnRep0.bb Gm12878.CTCF.narrowPeak
$ sort -k7gr Gm12878.CTCF.narrowPeak | head -n 500 > Gm12878.CTCF.top500.narrowPeak
$ genomepy install hg19 UCSC --annotation

$ gimme motifs Gm12878.CTCF.top500.narrowPeak gimme.CTCF -g hg19 --denovo

2021-05-25 09:59:02,874 - INFO - creating background (matched GC%)
Traceback (most recent call last):
  File "/home/neuhaus/miniconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/commands/motifs.py", line 87, in motifs
    create_background_file(
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/background.py", line 121, in create_background_file
    m = MatchedGcFasta(inputfile, genome, number=number, size=size)
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/background.py", line 577, in __init__
    matched_gc_bedfile(tmpbed, matchfile, genome, number, size=size)
  File "/home/neuhaus/miniconda3/envs/gimme/lib/python3.9/site-packages/gimmemotifs/background.py", line 510, in matched_gc_bedfile
    fraction = number / len(gc)
ZeroDivisionError: division by zero

**Installation information:**
 - OS: CentOS Linux 7 (Core)
 - Installation conda (conda 4.10.1)
 - gimmemotifs: 0.15.3

Thanks for your help,
Florian

**Comment by simonvh** [comment]
Hi Florian, 

I've checked and cannot reproduce the error, the tutorial seems to run fine on my side. Let's try to find the issue. Can  you try:

1) Deleting `~/.cache/gimmemotifs/` and running the `gimme` command again.
2) Try running `gimme background test.fa genomic -n 1 -s 10 -g hg19 -f fa`. The output file `test.fa` should contain one sequence of length 10.

**Comment by fneuh** [comment]
1. Deleting the cache and re-running didn't help, I got the same error

2. This worked!
$ cat test.fa
>chr14:41811982-41811992
ggcttgcaaa

**Comment by simonvh** [comment]
Hmm. The fact that 2 worked means your genome is installed and usable by GimmeMotifs.

Can you post the output of `conda list`, when run it inside the `gimme` conda environment?

**Comment by fneuh** [comment]
packages in environment at /home/neuhaus/miniconda3/envs/gimme:

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
abseil-cpp                20210324.1           h9c3ff4c_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow-cpp                 4.0.0           py39h6ac3dd5_3_cpu    conda-forge
aws-c-cal                 0.5.7                h3622835_1    conda-forge
aws-c-common              0.5.11               h7f98852_0    conda-forge
aws-c-event-stream        0.2.7                h5011166_5    conda-forge
aws-c-io                  0.9.12               h7aa3e40_2    conda-forge
aws-checksums             0.1.11               hc0e0e8b_6    conda-forge
aws-sdk-cpp               1.8.186              h9ad65fb_2    conda-forge
bedtools                  2.30.0               h7d7f7ad_1    bioconda
biofluff                  3.0.4                      py_0    bioconda
biopython                 1.78             py39h3811e60_2    conda-forge
boltons                   20.2.1             pyh9f0ad1d_0    conda-forge
boost-cpp                 1.74.0               hc6e9bd1_3    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
bucketcache               0.12.1           py39hde42818_2    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
cffi                      1.14.5           py39he32792d_0    conda-forge
chardet                   4.0.0            py39hf3d152e_1    conda-forge
click                     8.0.1            py39hf3d152e_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
configparser              5.0.2              pyhd8ed1ab_0    conda-forge
cryptography              3.4.7            py39hbca0aa6_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
dinamo                    1.0                  hee3b9ab_1    bioconda
diskcache                 5.2.1              pyh44b312d_0    conda-forge
expat                     2.2.10               h9c3ff4c_0    conda-forge
feather-format            0.4.1              pyh9f0ad1d_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py39hf3d152e_3    conda-forge
gadem                     1.3.1                h779adbc_3    bioconda
genomepy                  0.9.3                      py_0    bioconda
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
ghostscript               9.54.0               h9c3ff4c_1    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gimmemotifs               0.15.3           py39h8f06ca0_0    bioconda
glib                      2.68.2               h9c3ff4c_0    conda-forge
glib-tools                2.68.2               h9c3ff4c_0    conda-forge
glog                      0.5.0                h48cff8f_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
grpc-cpp                  1.37.1               h2519f57_2    conda-forge
gst-plugins-base          1.18.4               hf529b03_2    conda-forge
gstreamer                 1.18.4               h76c114f_2    conda-forge
harfbuzz                  2.8.1                h83ec7ef_0    conda-forge
homer                     4.11            pl5262h7d875b9_4    bioconda
htseq                     0.13.5           py39h70b41aa_1    bioconda
htslib                    1.12                 h9093b5e_1    bioconda
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.1            py39h1a9c180_1    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.76.1               h2574ce0_2    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libglib                   2.68.2               h3e27bee_0    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.1                h7f98852_0    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libllvm11                 11.1.0               hf817b99_2    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.3                 hd57d9b9_0    conda-forge
libprotobuf               3.16.0               h780b84a_0    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libthrift                 0.14.1               he6d91bd_1    conda-forge
libtiff                   4.2.0                hbd63e13_2    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxgboost                1.4.0                h9c3ff4c_0    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libxslt                   1.1.33               h15afd5d_2    conda-forge
llvmlite                  0.36.0           py39h1bbdace_0    conda-forge
logbook                   1.5.3            py39h3811e60_4    conda-forge
logomaker                 0.8                pyh864c0ab_1    bioconda
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                2.0.1            py39h3811e60_0    conda-forge
matplotlib                3.4.2            py39hf3d152e_0    conda-forge
matplotlib-base           3.4.2            py39h2fa2bec_0    conda-forge
meme                      5.3.0           py39pl5262heb7a276_2    bioconda
mpi                       1.0                     openmpi    conda-forge
mysql-common              8.0.23               ha770c72_2    conda-forge
mysql-connector-c         6.1.11            h6eb9d5d_1007    conda-forge
mysql-libs                8.0.23               h935591d_2    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
norns                     0.1.5              pyh864c0ab_1    bioconda
nose                      1.3.7                   py_1006    conda-forge
nspr                      4.30                 h9c3ff4c_0    conda-forge
nss                       3.65                 hb5efdd6_0    conda-forge
numba                     0.53.1           py39h4292f66_0    conda-forge
numpy                     1.20.3           py39hdbf815f_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjdk                   11.0.9.1             h5cc2fde_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openmpi                   4.1.1                hbfc84c5_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
orc                       1.6.7                h89a63ab_2    conda-forge
palettable                3.3.0                      py_0    conda-forge
pandas                    1.2.4            py39hde0f152_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
pathlib                   1.0.1            py39hf3d152e_4    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-algorithm-cluster    1.58            pl526h14c3975_0    bioconda
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-cgi                  4.44            pl526h14c3975_1    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-dbi                  1.642                   pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-file-which           1.23                    pl526_0    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-template        2.97                    pl526_1    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-log-log4perl         1.49                    pl526_0    bioconda
perl-math-cdf             0.1             pl526h14c3975_5    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526ha1d75be_1002    conda-forge
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pillow                    8.2.0            py39hf95b381_1    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
prosampler                1.0                  hc9558a2_0    bioconda
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py-xgboost                1.4.0            py39hf3d152e_0    conda-forge
pyarrow                   4.0.0           py39h3ebc44c_3_cpu    conda-forge
pybedtools                0.8.2            py39h39abbe0_1    bioconda
pybigwig                  0.3.18           py39h015b436_1    bioconda
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyfaidx                   0.5.9.5            pyh3252c3a_0    bioconda
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py39hf3d152e_7    conda-forge
pyqt-impl                 5.12.3           py39h0fcd23e_7    conda-forge
pyqt5-sip                 4.19.18          py39he80948d_7    conda-forge
pyqtchart                 5.12             py39h0fcd23e_7    conda-forge
pyqtwebengine             5.12.1           py39h0fcd23e_7    conda-forge
pysam                     0.16.0.1         py39h051187c_3    bioconda
pysocks                   1.7.1            py39hf3d152e_3    conda-forge
python                    3.9.4           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-xxhash             2.0.2            py39h3811e60_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39h3811e60_0    conda-forge
qnorm                     0.7.0              pyh44b312d_0    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
re2                       2021.04.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
represent                 1.6.0            py39h07f9747_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
s2n                       1.0.8                h9b69904_0    conda-forge
scikit-learn              0.24.2           py39h4dfa638_0    conda-forge
scipy                     1.6.3            py39hee8e79c_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
statsmodels               0.12.2           py39hce5d2b2_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   6.1              py39h3811e60_1    conda-forge
tqdm                      4.61.0             pyhd8ed1ab_0    conda-forge
trawler                   2.0                  hdfd78af_4    bioconda
tzdata                    2021a                he74cb21_0    conda-forge
ucsc-bedtogenepred        377                  h0b8a92a_2    bioconda
ucsc-bigbedtobed          377                  h0b8a92a_2    bioconda
ucsc-genepredtobed        377                  h0b8a92a_4    bioconda
ucsc-genepredtogtf        377                  h0b8a92a_4    bioconda
ucsc-gff3togenepred       377                  h0b8a92a_2    bioconda
ucsc-gtftogenepred        377                  h0b8a92a_4    bioconda
ucx                       1.9.0                h13c9de0_1    conda-forge
unzip                     6.0                  h7f98852_2    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
weeder                    2.0                  h7d875b9_5    bioconda
wget                      1.20.1               h22169c7_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xdg                       5.0.2              pyhd8ed1ab_0    conda-forge
xgboost                   1.4.0            py39hf3d152e_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.1                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xxhash                    0.8.0                h7f98852_3    conda-forge
xxmotif                   1.6                  h2d50403_2    bioconda
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by simonvh** [comment]
This is really strange. All you dependencies seem to be in order.

Can you try to install the development version of GimmeMotifs, to see if that helps (I'm really out of ideas here):

```
conda activate gimme
pip install git+https://github.com/vanheeringen-lab/gimmemotifs.git@develop
# run gimme command again
```

**Comment by fneuh** [comment]
Hi, sorry for not having written back in a while.. I tried it with the development version of gimmemotifs, but that also did not work.

I also installed gimmemotifs version v0.14.4 and tried running it with that, which also didn't help.. 

I will try to run this on another server and see if I get the same error there.

**Comment by simonvh** [comment]
@fneuh any update on this?

**Comment by mdozmorov** [comment]
This error may be due to some regions being long. Encountered the same error, troubleshooting involved starting with a few regions and increasing until the error occurred. Not sure what's the reasonable length threshold.
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/user/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/cli.py", line 746, in cli
    args.func(args)
  File "/home/user/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/commands/pfmscan.py", line 19, in pfmscan
    scan_to_file(
  File "/home/user/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 401, in scan_to_file
    for line in command_scan(
  File "/home/user/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 317, in command_scan
    s.set_threshold(fpr=fpr, threshold=cutoff)
  File "/home/user/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 989, in set_threshold
    df = self._threshold_from_seqs(scan_motifs, seqs, fpr).set_index(
  File "/home/user/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 724, in _threshold_from_seqs
    for gc_bin, result in zip(
  File "/home/user/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 1199, in _scan_sequences_with_motif
    for ret in self._scan_jobs(scan_func, seqs):
  File "/home/user/miniconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 1230, in _scan_jobs
    for i in range(math.ceil(len(scan_seqs) / chunksize)):
ZeroDivisionError: division by zero
```
