### ISSUE TITLE
Adjust the figure size of maelstrom heatmap

### ISSUE THREAD

**Issue by lynnyummy** [vanheeringen-lab/gimmemotifs#194]
Hi, I want to plot the heatmap of MaelstromResult. However I cannot print all the motifs names of each row even I adjusted  the size of heatmap.
`mr.plot_heatmap(figsize=(20, 20),threshold=1)`
`mr.plot_heatmap(figsize=(6, 6),threshold=1)`
it can only change the size of heatmap not the labels as the followings,

![image](https://user-images.githubusercontent.com/10953976/124399692-0dc50700-dd15-11eb-8826-b18620b899ca.png)
![image](https://user-images.githubusercontent.com/10953976/124399701-1c132300-dd15-11eb-97b4-caf3d1cb2e2a.png)

Could you please help to give any advice on how to adjust the heatmap in python? Or if I can use R to plot this heatmap?  
Thank you very much!

**Comment by simonvh** [comment]
Hi @lynnyummy .. yeah generating nice heatmaps is a bit of trial and error. By default, the TF names are shortened, as otherwise some rows may end up being very long.

If you are more familiar with R, you can also use that. You'll need to load the `final.out.txt` file in R, and select the columns you want to use for plotting. To be consistent with these images, you'll need to use the `z-score` columns. However, then you need to link up the motif names in `final.out.txt` with the factors, based on the info in `nonredundant.motifs.motif2factors.txt`.
Maybe @JGASmits has some tips on how to plot heatmaps in R for this data :)

**Comment by lynnyummy** [comment]
> Hi @lynnyummy .. yeah generating nice heatmaps is a bit of trial and error. By default, the TF names are shortened, as otherwise some rows may end up being very long.
> 
> If you are more familiar with R, you can also use that. You'll need to load the `final.out.txt` file in R, and select the columns you want to use for plotting. To be consistent with these images, you'll need to use the `z-score` columns. However, then you need to link up the motif names in `final.out.txt` with the factors, based on the info in `nonredundant.motifs.motif2factors.txt`.
> Maybe @JGASmits has some tips on how to plot heatmaps in R for this data :)

Hi @simonvh ,thanks for your reply! I used R to plot the heatmap, and find in the `final.out.txt` contains 190 motifs (showed below), but in the heatmap of MaelstromResult only has 35 rows with multi-labels. So the ` heatmap of MaelstromResult ` is the heatmap of factors, and the sum of the z-scores of all the corresponding motifs?
![image](https://user-images.githubusercontent.com/10953976/124675595-d8571f80-deb4-11eb-9a35-72b02bc692ee.png)

**Comment by JGASmits** [comment]
hi @lynnyummy , Ive attached some R code which I generally use to vizualize maelstrom results as a heatmap. It selects either the top 20/x of most variable motifs, or all motifs with a certain zscore variance. When multiple (curated) TFs map to a single motif, it will list all potential TFs seperated by a "_".  If no TFs are linked to a motif it will show the motif name instead. It uses the excellent "Complex Heatmap" package for vizualization (which you will need to install before running my script). If you want to alter more about the heatmap, take a look at their documentation:  https://jokergoo.github.io/ComplexHeatmap-reference/book/
If anything isnt clear please let me know! Gr Jos

`library('ComplexHeatmap')

maelstrom_motifs_heatmap <- function(maelstrom_output = './final.out.txt',
                                     motifs_2_factors= './gimme.vertebrate.v5.0.motif2factors.txt',
                                     pdf_location= './maelstrom_heatmap.pdf',
                                     TF_or_motif='TF',# or 'motif'
                                     filtering= 'topn',#or 'zscore'
                                     n_top=20,
                                     variance_cutoff=3,
                                     rownames_size=12,
                                     colnames_size=12,
                                     only_curated='Y',# or anything else if including all TF_motif interactions
                                     heatmap_widht = 7,
                                     heatmap_height = 7
                                     ) {
  # Generate a complex heatmap from a gimme maelstrom result
  # takes the output file from maelstrom 'final.out.txt', the motifs2factors file from gimme maelstrom, and the pdf output location.
  # it has multiple methods of selectin wich motifs to plot. Either the topx of motifs with the highest variance, or all motifs above
  # a certain zscore threshold 
  
  Rowvar <- function(x, ...) {
    rowSums((x - rowMeans(x, ...))^2, ...)/(dim(x)[2] - 1)
  }
  
  df <- read.csv(maelstrom_output, sep = '\t', stringsAsFactors=FALSE)
  zscores <- (df[,grepl('z.score', colnames(df))])
  rownames(zscores) <-  df$X
  zscores$variance <- Rowvar(zscores)
  zscores$percentage <- df[,grepl('with.motif', colnames(df))]
  if (TF_or_motif == 'TF'){
    print('converting_motif_to_TFs')
    motif2TF <- read.csv(motifs_2_factors, sep = '\t', stringsAsFactors=FALSE)
    motif2TF$Factor = toupper(motif2TF$Factor)
    
    if (only_curated == 'Y'){motif2TF <- motif2TF[motif2TF$Curated == only_curated,]}
    motif2TF <- unique(motif2TF[c('Motif','Factor')])
    Motif2TFs <- aggregate(motif2TF$Factor, list(motif2TF$Motif), paste, collapse="_")
    Motif2TFs <- na.omit(Motif2TFs)
    colnames(Motif2TFs) <- c('Motif','TFs')
    zscores$Motif = rownames(zscores)
    zscores <- merge(zscores, Motif2TFs, by = 'Motif', all.x= T)
    zscores$TFs <- ifelse(is.na(zscores$TFs), zscores$Motif, zscores$TFs)
    zscores$ID <- make.names(zscores$TFs, unique = TRUE)
    rownames(zscores) <- zscores$ID

  }
  
  zscores <- zscores[order(abs(zscores$variance), decreasing = T),]
  
  if (filtering == 'topn'){
    zscores = head(zscores, n_top)
  }
  if (filtering == 'zscore'){
    zscores <- zscores[zscores$variance > variance_cutoff,]
  }
  perc_annotation <- rowAnnotation(percentage = zscores$percentage)
  matrix <- zscores[, !names(zscores) %in% c("percentage", "variance","Motif",'TFs','TF','ID')]
  rownames(matrix) <- rownames(zscores)
  motifs_heatmap <- Heatmap(as.matrix(matrix),
                            cluster_columns = T,
                            cluster_rows = T,
                            show_row_names = T,
                            row_km_repeats = 100,
                            column_km_repeats = 100,
                            right_annotation = perc_annotation,
                            row_names_gp = grid::gpar(fontsize = rownames_size),
                            column_names_gp =grid::gpar(fontsize = colnames_size)

  )

  #pdf('/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/heatmap.pdf',width=heatmap_widht,height=heatmap_height,paper='special')
  pdf(pdf_location,width=heatmap_widht,height=heatmap_height,paper='special')
  print(motifs_heatmap)
  dev.off()
}`

Example of how to run the code:
`
maelstrom_motifs_heatmap(maelstrom_output = "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/Epi_fate_specifiers/analysis/CREs_model/2021-28-05/maelstrom/TP_enhancers_all/final.out.txt",
                         motifs_2_factors = "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/Epi_fate_specifiers/analysis/CREs_model/2021-28-05/maelstrom/TP_enhancers_all/gimme.vertebrate.v5.0.motif2factors.txt",
                         pdf_location = "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/Heatmap_V5.pdf",
                         TF_or_motif='motif',# or 'motif'
                         rownames_size=4,
                         colnames_size=4,
                         filtering= 'zscore',
)`

**Comment by lynnyummy** [comment]
> hi @lynnyummy , Ive attached some R code which I generally use to vizualize maelstrom results as a heatmap. It selects either the top 20/x of most variable motifs, or all motifs with a certain zscore variance. When multiple (curated) TFs map to a single motif, it will list all potential TFs seperated by a "_". If no TFs are linked to a motif it will show the motif name instead. It uses the excellent "Complex Heatmap" package for vizualization (which you will need to install before running my script). If you want to alter more about the heatmap, take a look at their documentation: https://jokergoo.github.io/ComplexHeatmap-reference/book/
> If anything isnt clear please let me know! Gr Jos
> 
> (I'm gonna attach the code as a file, the annotation otherwise goes whack)
> [maelstrom_heatmap_script.txt](https://github.com/vanheeringen-lab/gimmemotifs/files/6777778/maelstrom_heatmap_script.txt)

Hi @JGASmits, thank you so much for your explanation and the R code! That's very much helpful!  I will have a try and let you know the output! 

Thank you!!
