### ISSUE TITLE
Add config method to list available motif libraries

### ISSUE THREAD

**Issue by laserson** [vanheeringen-lab/gimmemotifs#198]
AFAICT there is no way to list all the libraries that are "batteries-included" with a gimmemotifs install. I think this code snippet will do it.

```python
def list_gimmemotif_included_libraries():
    """Return a list of all motif libraries included with gimmemotifs

    The returned strings are suitable for use with `gimmemotifs.motif.read_motifs`
    """
    library_files = glob(str(Path(MotifConfig().get_motif_dir()).resolve() / "*.pfm"))
    return sorted([Path(p).name for p in library_files])
```

You could potentially add this type of thing to the `MotifConfig` object if that makes sense to you. Happy to submit a PR if it'll be accepted.

**Comment by simonvh** [comment]
You are right, there is currently not such thing. 

There is functionality to download motif databases (which I run once in a while to update databases) in 
https://github.com/vanheeringen-lab/gimmemotifs/blob/master/gimmemotifs/db/__init__.py

You can run the following code to get the databases:

```
from gimmemotifs.db import MotifDb
MotifDb.list_databases()
```

However! This is only used to download, this command doesn't list the versions of the databases that are actually provided. Maybe this would actually be good place to incorporate the type of command that you illustrate above.  Would have to think about the naming to indicate motif database *providers* versus installed motif databases.

We'd certainly be happy to accept a PR, once we decide on the best place to put it.

**Comment by laserson** [comment]
Great, let me know!

Personally, since this output depends on the installed configuration, I'd suggest adding it as a method to `MotifConfig`. It seems like `MotifDb` is more of an "internal" utility.
