### ISSUE TITLE
A problem about input peak select for maelstrom

### ISSUE THREAD

**Issue by shangguandong1996** [vanheeringen-lab/gimmemotifs#202]
Hi, 

I have some questions about input data of maelstrom. **Is there any limit about input peak set select ?**. I noticed you use the most variable peak as input peak count data. I am just wondering why you select the most variable peak.

**And I am wondering whether I can use maelstrom in not most variable peak set**. For example, I have a interesting gene set, and I extract nearby peak and want to see the motif tendency in this peak set during different samples.

And the third question is that If I have two peak set: set A and set B, **Will the result of maelstrom be much different?** For example, TF C2C2 value will be 4-2-1-0 in set A while C2C2 value will be 0-1-2-4 in set B.  

Best wishes
Guandong Shang

**Comment by simonvh** [comment]
There is a practical limit, as in that memory and CPU usage increase with more region. We've successfully run maelstron ~50-100,000 regions, but that is on a high-memory server. That's the main reason!

For the second question, I'm not sure I understand. You can use maelstrom on any set of regions, however, what you will find depends on what your input is. For instance, you can use the following type of input:

```
chr:start-end   gene_set1
chr:start-end   gene_set1
chr:start-end   gene_set2
chr:start-end   gene_set2
chr:start-end   gene_set3
chr:start-end   gene_set3
```

Where maelstrom will identify the difference between three peak sets. But I'm not sure if that is what you mean.

For the third question, what do you mean by C2C2 value? In general, results will be similar if the peak sets are similar. For instance, if you use ATAC-seq peaks of one replicate versus the peaks from another replicate.

**Comment by shangguandong1996** [comment]
Thanks for your reply, simon. I am sorry what I say may confuse you.

What I actually care is the biology meaning of input peak select. If I can select any peak set, I can select most variable peak, all peak locating in Chr1, all peak locating in Chr2, or all peak located nearby some gene. 
I am just wondering whether maelstrom can produce meaningful result according to the selected input select. 

By the way, should the input peak set number should be big? I noticed you use some regression in maelstron code, if the sample number(peak number) is small, I am wondering whehter the final result will be not robust.

Best wishes

Guandong Shang

**Comment by simonvh** [comment]
Yes, maelstrom gives better results when you have a reasonably big peak set. For instance, we usually see improvements if you go from 1,000 to 10,000 peaks. However, this also depends on how strong the motif signals are.

As for you question on selecting peaks, I don't have the answer! It may influence the results, however, how much I can't say. Usually, I go by the rule of thumb that patterns/motifs of interest should be robust to the selection. So if you have a motif that only comes up with a very specific set of parameters I would be careful about overinterpreting that.

**Comment by shangguandong1996** [comment]
For example, I randomly select 1000 peak from the total peak set. I can say this peak set is meaningless from a biological point of view and the weight of each TF should be same. But if I input this peak set into maelstrom, it still gives z-score for each TF, and some TF will be postive in some sample while some TF will be negative becuase maelstrom using the inverse normal transformation to convert ranked coefficent into z-score. But it seems that this positive and negative score can not represent the ture meaning.

Please forgive me if I misunderstand something.

Best wishes

Guandong Shang
