### ISSUE TITLE
gimme scan negative region lenght 

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/gimmemotifs#212]
When providing gimme scan with a bedfile with:
chrom:end-start

instead of 
chrom:start-end

gimme scan doesn't crash but instead calculates the same score for each region.
Crashing or an error would prevent people like me that make such silly mistakes a bit of a headache trying to find what is going on.  :)

**Comment by simonvh** [comment]
Also related to #211, where a negative start results in errors. I think the region parsing should generally either warn and skip in case of something unexpected, or give a very informative error message.

**Comment by siebrenf** [comment]
You could catch this on the gimme side (if the sequence length is 0), but it doesn't make sense that genomepy outputs these regions either. So the next version of genomepy  (>0.10.0) will skip both these kinds of bad regions:

```
import genomepy
g = genomepy.Genome("Xenopus_tropicalis_v9.1")
g.track2fasta(["1:1-5", "1:6-2", "1:-1-2", "1:1-2a"])
22:04:32 | WARNING | Skipping region that ends before it starts: '1:6-2'
22:04:32 | WARNING | Skipping region that cannot be parsed: '1:-1-2'
22:04:32 | WARNING | Skipping region that cannot be parsed: '1:1-2a'
[>1:1-5
actg]

```

if the function input is a file, its basename will also be printed in the warning.
