### ISSUE TITLE
develop branch: deprecation warnings are going to stdout

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/gimmemotifs#230]
**Describe the bug**
On the develop branch (commit b7e153c, from dec 1), `motif.to_pwm()` returns a deprecation warning that is caught by `"{}\n".format(m.to_pwm())`. So I gues its going to stdout instead of stderr.

**Expected behavior**
Deprecation warnings to stderr. Using `logger.warning()` with the warnings should fix this.

**Installation information (please complete the following information):**
 - OS: Linux
 - Installation: `git clone` + `pip install -e . `
 - Version: develop branch v0.16.1+79.gb7e153c

**Comment by simonvh** [comment]
Can you give a minimal example of this? There was a bug with `motif.to_pwm()` where it didn't return the actual formatted motif, which I've fixed now, but the warning is logged to stderr. (This is different in testing, where warnings are specifically caught and reported)

**Comment by siebrenf** [comment]
in the current version of the develop branch there are two functions `Motif.to_pwm()` (one in `motif.py`, one in `motif/__init__.py`).
when I run a minimal example, I dont get the warning at all anymore, so I guess the `motif.py` instance is used. This also means there's no error 🚀 

```python
from gimmemotifs import __version__
from gimmemotifs.motif import read_motifs

print(__version__)

pfmfile = None
_motifs = read_motifs(pfmfile, as_dict=True)

motifs = list(_motifs.values())
for m in motifs:
    print("{}\n".format(m.to_pwm()))
    break
```
returns
```python
Backend Qt5Agg is interactive backend. Turning interactive mode on.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-siebrenf'
0.16.1+102.gb70da7a
<_io.TextIOWrapper name='/home/siebrenf/git/gimmemotifs/gimmemotifs/../data/motif_databases/gimme.vertebrate.v5.0.pfm' mode='r' encoding='UTF-8'>
>GM.5.0.Sox.0001
0.7194	0.0800	0.1109	0.0897
0.9232	0.0082	0.0072	0.0614
0.0058	0.9176	0.0087	0.0679
0.9830	0.0040	0.0040	0.0090
0.9749	0.0053	0.0137	0.0061
0.1488	0.0060	0.0177	0.8275
```

bonus: same issue as in #231 happens here too!

**Comment by siebrenf** [comment]
here's a better test script:
```python
from contextlib import redirect_stdout, redirect_stderr
import io

# capture stdout + stderr
err = io.StringIO()
out = io.StringIO()
with redirect_stderr(err), redirect_stdout(out):
    # the MRE
    from gimmemotifs import __version__
    from gimmemotifs.motif import read_motifs
    
    print("version:", __version__)
    
    pfmfile = None
    _motifs = read_motifs(pfmfile, as_dict=True)
    motifs = list(_motifs.values())
    print("{}\n".format(motifs[0].to_pwm()))

# print captures
print("\nstdout:\n", out.getvalue())
print("\nstderr:\n", err.getvalue())

```
returns
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-siebrenf'

stdout:
 Backend Qt5Agg is interactive backend. Turning interactive mode on.
version: 0.16.1+102.gb70da7a
<_io.TextIOWrapper name='/home/siebrenf/git/gimmemotifs/gimmemotifs/../data/motif_databases/gimme.vertebrate.v5.0.pfm' mode='r' encoding='UTF-8'>
>GM.5.0.Sox.0001
0.7194	0.0800	0.1109	0.0897
0.9232	0.0082	0.0072	0.0614
0.0058	0.9176	0.0087	0.0679
0.9830	0.0040	0.0040	0.0090
0.9749	0.0053	0.0137	0.0061
0.1488	0.0060	0.0177	0.8275



stderr:
 
```


The deprecation warning is gone, so the issue is technically resolved. However, there are multiple messages printed to stdout that really shouldn't be.

**Comment by siebrenf** [comment]
btw, the `QStandardPaths` comes from gimme too. It's harmless, but should also be printed on stderr instead of this untyped... something...

**Comment by simonvh** [comment]
```
stdout:
 version: 0.16.1+97.g53ca783.dirty
>GM.5.0.Sox.0001
0.7194  0.0800  0.1109  0.0897
0.9232  0.0082  0.0072  0.0614
0.0058  0.9176  0.0087  0.0679
0.9830  0.0040  0.0040  0.0090
0.9749  0.0053  0.0137  0.0061
0.1488  0.0060  0.0177  0.8275



stderr:
 ```

No extraneous output on my side. #231 is fixed.
` Backend Qt5Agg is interactive backend. Turning interactive mode on.` -> this is related to the matplotlib backend. This is not a warning that gimme can control. 

`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-siebrenf'` -> This has to do with your login env / shell. This is a default global env that *should* be set by default.  This is also something outside our code.

I think that means we can close this issue?

**Comment by siebrenf** [comment]
Ah OK! `QStandardPaths` might be my WSL's lack of default settings then, and the `Backend` message seems to happen in the interactive python environment. Weird that Matplotlib doesn't print this to stderr, but it shouldn't interfere with CLI commands...

Piping `gimme scan` to file now results in a proper file again!
