### ISSUE TITLE
Error in creating statistics report "_translate() takes 1 positional argument but 3 were given"

### ISSUE THREAD

**Issue by sqhang** [vanheeringen-lab/gimmemotifs#242]
**Describe the bug**
When running gimmemotifs de-novo motif discovery with the example file, TAp73alpha.bed, de-novo motif discovery finished but an error occured in creating statistics report. It says "TypeError: _translate() takes 1 positional argument but 3 were given". 

**To Reproduce**
Download the example file,  TAp73alpha.bed, from [https://figshare.com/articles/dataset/GimmeMotifs_example_data/5182897], and download the hg19 reference genome (provider UCSC) using genomepy. Then, run the command 
`gimme motifs TAp73alpha.bed gimme_out/gimme.p73 -g hg19 -a small -t Homer,MDmodule,BioProspector` 

**Expected behavior**
A full report including the statistics report should be outputted. 

**Error logs**
scanning:   0%|          | 0/1000 [00:00<?, ? sequences/s]
scanning:   0%|          | 1/1000 [00:00<07:37,  2.19 sequences/s]
scanning: 100%|██████████| 1000/1000 [00:00<00:00, 2010.79 sequences/s]
2022-01-22 19:51:04,657 - INFO - creating statistics report
/home/miniconda3/x86/envs/gimme3/lib/python3.9/site-packages/pandas/core/arraylike.py:364: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/home/miniconda3/x86/envs/gimme3/lib/python3.9/site-packages/pandas/io/formats/style.py:2817: RuntimeWarning: invalid value encountered in double_scalars
  norm = colors.Normalize(smin - (rng * low), smax + (rng * high))
Traceback (most recent call last):
  File "/home/miniconda3/x86/envs/gimme3/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/miniconda3/x86/envs/gimme3/lib/python3.9/site-packages/gimmemotifs/cli.py", line 746, in cli
    args.func(args)
  File "/home/miniconda3/x86/envs/gimme3/lib/python3.9/site-packages/gimmemotifs/commands/motifs.py", line 278, in motifs
    roc_html_report(
  File "/home/miniconda3/x86/envs/gimme3/lib/python3.9/site-packages/gimmemotifs/report.py", line 1018, in roc_html_report
    ExtraStyler(df)
  File "/home/miniconda3/x86/envs/gimme3/lib/python3.9/site-packages/pandas/io/formats/style.py", line 272, in render
    return self._render_html(sparse_index, sparse_columns, **kwargs)
  File "/home/miniconda3/x86/envs/gimme3/lib/python3.9/site-packages/pandas/io/formats/style_render.py", line 123, in _render_html
    d = self._translate(sparse_index, sparse_columns)
TypeError: _translate() takes 1 positional argument but 3 were given

**Installation information (please complete the following information):**
 - OS: Linux 
 - Installation: mamba installation
 - Version 0.17.0 (py39h8f06ca0_1)
 - Python: 3.9.7
 - Pandas: 1.3.5

**Comment by siebrenf** [comment]
I think Simon fixed this bug in the develop branch. You can install this with `pip install git+https://github.com/vanheeringen-lab/gimmemotifs.git@develop`

**Comment by sqhang** [comment]
Hi, thanks for sharing with me the development version! That bug has been fixed now. 

There are still some runtime warnings, `/home/BCM/u239486/miniconda3/x86/envs/gimme3/lib/python3.9/site-packages/pandas/core/arraylike.py:397: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/home/BCM/u239486/miniconda3/x86/envs/gimme3/lib/python3.9/site-packages/pandas/io/formats/style.py:3558: RuntimeWarning: invalid value encountered in double_scalars
  norm = mpl.colors.Normalize(smin - (rng * low), smax + (rng * high))
`  

I think we shouldn't worry too much about those warnings for the purpose of motif. Do you have any comments on that? Thanks!
