### ISSUE TITLE
set_genomes function in Scanner() cannot be passed additional arguments for class Genome

### ISSUE THREAD

**Issue by roskamsh** [vanheeringen-lab/gimmemotifs#285]
**Description of bug:**
When I initialize an object of class `Scanner()` and use the `set_genomes()` function on that object, I am unable to pass in a `genomes_dir` that is not either the default genomepy genomes directory or defined in the genomepy configuration file (under `genomes_dir`). This does not allow customizability if you are unable to run either of these options in a streamlined way.

**To reproduce:**
1. Install genomepy genome of your choosing (in my case, hg19) to a directory that is *not* `~/.local/share/genomes` (specified with the `--genomes_dir` flag)

`genomepy install --annotation hg19 --genomes_dir /path/to/alternate/genomes_dir`

2. Initialize an object of class Scanner() and set_genome() on this object

`from gimmemotifs.scanner import Scanner`
`scanner = Scanner()`
`scanner.set_genome("hg19")`

**Error:**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/conda_env/nopeak-utils/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 1095, in set_genome
    Genome(genome)
  File "/path/to/conda_env/nopeak-utils/lib/python3.8/site-packages/genomepy/genome/__init__.py", line 51, in __init__
    self.genomes_dir = get_genomes_dir(genomes_dir, check_exist=False)
  File "/path/to/conda_env/nopeak-utils/lib/python3.8/site-packages/genomepy/utils.py", line 50, in get_genomes_dir
    raise FileNotFoundError("Please provide or configure a genomes_dir")
FileNotFoundError: Please provide or configure a genomes_dir

- currently, `set_genome()` only takes a single argument, which is the string associated with the genome build that is installed through `genomepy install`
- This should take all of the arguments that the class `Genome()` takes in order to increase customizability of the function `set_genome()` (for example: `genomes_dir` and additional `*args` and `**kwargs` for `Fasta` class)

**Installation information (please complete the following information):**
 - OS: Linux
 - Installation: conda
 - Version: gimmemotifs v0.17.2

**Additional context**
I have a plan to fix this and am currently working on it in a forked repository. I will submit a merge request once completed and reference this issue.

**Comment by siebrenf** [comment]
Hey roskamsh, nice catch! You can specify the path to the genome, but I agree it's nice if you can just copy the genomepy API.

The genome can be used by a few different tools, so we really only want to get the genome's filepath from this function. I've implemented your idea, without unneeded args and kwargs in [f986e65](https://github.com/vanheeringen-lab/gimmemotifs/commit/f986e65f1ef58a1f2ab907a0a02dde5d66e6cf31), and added you as co-author of the commit!
