### ISSUE TITLE
Push most recent version (0.17.2) to gimmemotifs

### ISSUE THREAD

**Issue by roskamsh** [vanheeringen-lab/gimmemotifs#290]
Hi there,

Is there any chance you could please push the most recent build of gimmemotifs (v0.17.2) to pypi? 

Thank you so much!
Breeshey

**Comment by siebrenf** [comment]
Hey Breeshey, 

sorry for the long delay! I didn't have permissions to push to the Pypi repo earlier, but 0.17.2 and 0.18.0 are now up!
