### ISSUE TITLE
How gimme maelstrom final score was calculated 

### ISSUE THREAD

**Issue by crazyhottommy** [vanheeringen-lab/gimmemotifs#64]
Hi,

I saw in the output there are activity* files including different methods such as hypergeometric testing, randomforest etc. How the final score was calculated?

In my run with 4 different clusters in a bed file, the final score (html) reported that AP1 binding motif is enriched in cluster3 with scores of 4-5. the other clusters have a score of 0 or negative.

But when I use gimme scan to check how many AP1 motifs in each cluster, the number of motifs are not that different across clusters.

How is that possible?

Thanks!
Tommy

**Comment by simonvh** [comment]
This is indeed somewhat complicated. The individual predictors are combined using rank aggregation ([Kolde, 2012](https://www.ncbi.nlm.nih.gov/pubmed/22247279)). The score that is shown is the `-log10(p-value)`, where the p-value is corrected for multiple testing. However, I also repeat the rank aggregation with the ranking reversed. These are shown as negative, but where originally also positive. 

The different methods use different ways to rank the motifs. The hypergeometric test is the only one that uses motif counts. All the other methods use the PWM logodds score of the best match. What you could do is plot the motif scores of the AP1 motifs across the clusters using a box plot. I suspect you will see higher score in the clusters that had scores 4-5.

**Comment by simonvh** [comment]
Hey @crazyhottommy I just wanted to check if the explanation is clear enough that I can close this issue?
