### ISSUE TITLE
ImportError: cannot import name 'RLock'

### ISSUE THREAD

**Issue by FrancescoFerrari88** [vanheeringen-lab/gimmemotifs#69]
I am trying to install GimmeMotifs via conda. The process seems successful but when I run any command, I get the following error: " ImportError: cannot import name 'RLock' ".

**Comment by simonvh** [comment]
Hi Francesco, that's a new error to me! :-( Can you give me the output of `conda list` and of `conda info` and the steps you took to install GimmeMotifs?

**Comment by FrancescoFerrari88** [comment]
Hi Simon! To install, I issue the following command: "conda create -n gimme python=3 gimmemotifs". once the installation process is completed, I go for: " source activate gimme "
Please, find attached the output of conda list and conda info (after gimme has been activated). 
Thanks for your support!
[conda_info_gimmeEnv.txt](https://github.com/simonvh/gimmemotifs/files/2533377/conda_info_gimmeEnv.txt)
[conda_list_gimmeEnv.txt](https://github.com/simonvh/gimmemotifs/files/2533378/conda_list_gimmeEnv.txt)

ps. This error must be related with the cluster I am working on. When I install it with exactly the same commands on my PC (a Mac) everything runs smoothly.

**Comment by simonvh** [comment]
It might be that the conda channels are in the wrong order (this has been recently changes). Can you try to run this:

```
conda config --remove channels r
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

Remove the old installtion:

```
conda env remove -n gimme
```

And after that reinstall gimmemotifs.

**Comment by simonvh** [comment]
@FrancescoFerrari88 Did this work or do you still have problems?

**Comment by FrancescoFerrari88** [comment]
Hi Simon, sorry for the late replay. I followed your suggestion, but the same error occurs. I attach the complete error message hereunder. 
[gimme_error.txt](https://github.com/simonvh/gimmemotifs/files/2549381/gimme_error.txt)

**Comment by simonvh** [comment]
I'm afraid I can't really pin down the issue here. One last thing you can try is to install `logbook` and `gevent` in the environment at the same time:

```
$ conda activate gimme
$ conda install gevent logbook
```

It's a long shot but that *might* solve it.

**Comment by FrancescoFerrari88** [comment]
Hi Simon, this morning I tried to install gimmeMotifs once again, and everything went smooth. installation was successful and all commands work!
