### ISSUE TITLE
UnboundLocalError: local variable 'valid_bg' referenced before assignment

### ISSUE THREAD

**Issue by mdozmorov** [vanheeringen-lab/gimmemotifs#70]
Hi Simon,
I've followed the https://gimmemotifs.readthedocs.io installation instructions. The Conda installation on macOS Sierra 10.12.6 worked fine, environment activated, genome annotations installed. Attempt to run basic analysis results in an error:
```
$ gimme motifs CTCF.bed -g hg19 -n test1
Sorry, motif prediction tool MEME is not supported
```
Excluding MEME doesn't help:
```
$ gimme motifs CTCF.bed -g hg19 -n test1 -t Homer,BioProspector
Traceback (most recent call last):
  File "/Users/mdozmorov/miniconda2/envs/gimme/bin/gimme", line 513, in <module>
    args.func(args)
  File "/Users/mdozmorov/miniconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/motifs.py", line 69, in motifs
    gimme_motifs(args.inputfile, args.name, params)
  File "/Users/mdozmorov/miniconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/denovo.py", line 525, in gimme_motifs
    input_type, background = check_denovo_input(inputfile, params)
  File "/Users/mdozmorov/miniconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/validation.py", line 60, in check_denovo_input
    if not bg in valid_bg:
UnboundLocalError: local variable 'valid_bg' referenced before assignment
```
The head of my BED file:
```
chr1 850718 850942
chr1 856275 856499
chr1 862729 862953
chr1 864695 864919
chr1 872641 872865
chr1 889157 889381
chr1 889597 889821
chr1 900920 901144
chr1 907087 907311
chr1 956668 956892
```
Where to go from there?

Thanks,
Mikhail

**Comment by simonvh** [comment]
Hi Mikhail, thanks for reporting. This Error seems to be a bug. From what I see the input file format is not being recognized.

 Is your BED file space-separated by any chance? If that is the case, try with a tab-separated BED file.

**Comment by jonasungerback** [comment]
Hello,

I ran into the same problem and it turned out to be a missformatted bed-file. However, I also run into

`Sorry, motif prediction tool MEME is not supported` and the same for trawler which puzzles me even more. I have not resolved that but on my system the meme-command is called with lowercase letters. Is gimme looking for the phrase MEME I assume it will not find it? Trawler cannot be explained by that though if that would be the explanation?

Best,
Jonas

**Comment by mdozmorov** [comment]
Thank you, @simonvh, @jonasungerback, the problem is indeed the misformatted BED file - spaces instead of tabs. Happen sometimes when you got the data from collaborators.

Closing this issue. @jonasungerback, perhaps you can open a new one for your meme/trawler issue?
