### ISSUE TITLE
Sorry, motif prediction tool MEME is not supported

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/gimmemotifs#71]
This issue came up in #70  (@mdozmorov @jonasungerback)

It probably has to with the fact that for a while the Mac OS X conda build for meme didn't work, so the gimmemotifs package has disabled it by default. I will fix this for the next release. In the meantime you can edit the gimmemotifs config file (most likely `~/.config/gimmemotifs/gimmemotifs.cfg`), find the `[params]` section and add `MEME` to `available_tools`.

**Comment by simonvh** [comment]
Additionaly, you will have to set the `bin` variable under the `[MEME]` section to the right location (the binary installed by conda is not called `meme.bin` but `meme`)

**Comment by simonvh** [comment]
So I have added a section to the FAQ: https://gimmemotifs.readthedocs.io/en/master/faq.html#sorry-motif-prediction-tool-x-is-not-supported
With the new release (0.13.1) meme should work again.

**Comment by jonasungerback** [comment]
Thanks!
