### ISSUE TITLE
possible to use reference genome from bowtie?

### ISSUE THREAD

**Issue by chrisclarkson** [vanheeringen-lab/gimmemotifs#77]
Hi
GimmeMotifs has been installed on the cluster that I work on. But **to avoid taking up storage space**- it is preferred that I use a reference genome that is already installed- from bowtie.

I tried this:
`gimme scan ENCODE_ESC_peaks_formatted.fa -p jaspar.tab -g /..../ReferenceGenomes/Mus_musculus/UCSC/mm9/Sequence/WholeGenomeFasta/genome.fa -b > ENCODE_jaspar_gimme_motifs.bed`

But I got the error:

```
Genome not found. Have you installed your genome with genomepy?
See https://github.com/simonvh/genomepy for details.
Alternatively, you can specify a FASTA file.
```

Is it somehow possible to get gimme scan to search a genome from bowtie rather than install the genomepy one and use that?

**Comment by chrisclarkson** [comment]
Hi,
Thanks so much for your quick reply.
I checked that the reference genome path was correct and it is. Also I tried creating a symlink in the directory with the data:
```
ln -s /storage/projects/ReferenceGenomes/Mus_musculus/UCSC/mm9/Sequence/WholeGenomeFasta/genome.fa mm9fasta.fasta

gimme scan ENCODE_CTCF_ESC_peaks_formatted.fa -p jaspar_CTCF.tab -g mm9fasta -b
```

But I got the same error.

**Comment by simonvh** [comment]
Hm. A symlink would be my second suggestion. However, with a filename you would need to supply the full name, including extension.

In your example this would be:

```
ln -s /storage/projects/ReferenceGenomes/Mus_musculus/UCSC/mm9/Sequence/WholeGenomeFasta/genome.fa mm9fasta.fasta

gimme scan ENCODE_CTCF_ESC_peaks_formatted.fa -p jaspar_CTCF.tab -g mm9fasta.fasta -b
```

If that doesn't work, which version of GimmeMotifs and genomepy are you running?

```
genomepy --version
gimme -h
```

**Comment by chrisclarkson** [comment]
Hi so your shortcuts seems to work:

Hi- your trick seems to work:

```gimme scan ENCODE_CTCF_ESC_peaks_formatted.fa -p jaspar_CTCF.tab -g mm9fasta.fasta -b
# GimmeMotifs version 0.13.1
# Input: ENCODE_CTCF_ESC_peaks_formatted.fa
# Motifs: jaspar_CTCF.tab
# FPR: 0.01 (mm9fasta.fasta)
2019-05-27 10:25:29,647 - INFO - Using background: genome mm9fasta.fasta with length 1000
2019-05-27 10:25:35,366 - INFO - Determining FPR-based threshold```
But the process takes ~1min
But when I try to output the found hits to a file: `> results.txt`
the file is empty..

As for the version of genomepy:
```
genomepy --version
genomepy, version 0.5.5
[cc16956@compute-1-29 ~]$ gimme -h
type `gimme -h -h` for more details

usage: gimme [-h] <subcommand> [options]

    GimmeMotifs v0.13.1
    

positional arguments:
  {motifs,match,maelstrom,roc,cluster,background,threshold,location,scan,diff,logo,prediction}

optional arguments:
  -h, --help            show this help message and exit

   
    commands:
        motifs      predict new motifs
        maelstrom   find differential motifs
        scan        find known motifs
        roc         calculate/plot statistics
        match       find motif matches in database
        cluster     cluster similar motifs
        background  create a background file
        threshold   calculate motif scan threshold
        location    motif location histograms
        diff        compare motif frequency and enrichment
                    between fasta files
        logo        create sequence logo(s)
    
    type `gimme <command> -h` for more details
```
    
The start of the bowtie reference file that I'm using looks like:

```
>chr10
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

**Comment by simonvh** [comment]
So, GimmeMotifs and genomepy are both up-to-date, that's good.

The first time you run `gimme scan` with a certain FPR threshold (0,01 or 1% by default) for a certain input length (1000 in your case) it will take some more time to calculate the background score distribution. After that, it will be faster.

If the file is empty, that means no significant motif hits were found. You can try two things: 1) increase the FPR threshold using the `-f` argument. 2) use shorter sequences, I would recommend 200bp centered at the summit of the peaks.

**Comment by chrisclarkson** [comment]
ah I see ok thanks for your help and patience.

**Comment by simonvh** [comment]
Closing this issue, if you encounter any problems feel free to reopen or create a new issue.
