### ISSUE TITLE
Syntax error when running gimme roc

### ISSUE THREAD

**Issue by preethiperi** [vanheeringen-lab/gimmemotifs#79]
**Describe the bug**
I have a virtual environment running Python 3.7.3 and used pip to install numpy and gimme. I tried running the following command:
gimme roc input.fasta bg.fa > enriched_motifs.txt

The following output was seen:
Traceback (most recent call last):
  File "/path/to/bin/gimme", line 6, in <module>
    from gimme.generator import main
  File "/path/to/lib/python3.7/site-packages/gimme/__init__.py", line 1, in <module>
    from .app import App
  File "/path/to/lib/python3.7/site-packages/gimme/app.py", line 3, in <module>
    from .routes import Routes
  File "/path/to/lib/python3.7/site-packages/gimme/routes.py", line 119
    except IndexError, e:
                     ^
SyntaxError: invalid syntax

**To Reproduce**
1. Create a new pip virtual environment with Python 3
2. Run pip install numpy
3. Run pip install gimme
4. Try gimme roc input.fasta bg.fa > enriched_motifs.txt

**Expected behavior**
Enriched motifs listed in the output text file.

**Error logs**
Error logs listed above

**Installation information (please complete the following information):**
 - OS: macOS Mojave
 - Installation: pip
 - Version: pip 19.1.1, Python 3.7

**Comment by simonvh** [comment]
Hi @preethiperi, it look like you have installed the wrong package by accident. The package [gimme](https://pypi.org/project/gimme/) is a different package. The one to install is [gimmemotifs](https://pypi.org/project/gimmemotifs/). However, my suggestion would be to install gimmemotifs via bioconda, as this will install all the necessary dependencies (pip can only deal with Python dependencies).

**Comment by preethiperi** [comment]
Thank you so much! And thanks for responding so promptly :). Would it be possible for you guys to paste a requirements.txt file for those of us not using bioconda? (I know that's what you suggest, but personal experience has made me prefer pip a lot more, haha).

**Comment by simonvh** [comment]
There is a [requirements.txt](https://github.com/vanheeringen-lab/gimmemotifs/blob/master/requirements.txt), not sure how up to date it is. In case you would want to use any *de novo* motif tools you also also will need to install them yourself.

**Comment by preethiperi** [comment]
Got it, thanks! Also, statsmodels is not currently compatible with scipy 1.3.0, so using this requirements file might fail at the moment. Just a heads up!

Unrelated: is there any way to run any of the commands with a -verbose option? e.g. gimme roc [input file] [whatever else] -verbose

**Comment by simonvh** [comment]
There is not I'm afraid. There is currently no command-line option to set the log level to debug. This would be a useful addition.
