### ISSUE TITLE
Problem running gimme scan

### ISSUE THREAD

**Issue by stefanucci-luca** [vanheeringen-lab/gimmemotifs#80]
**Describe the bug**
I'd like to annotate the directionality of some CTCF motif. I'm using  ```gimme scan MK_CTCF_From_Romina_hg38_c10.0_l245_g100_peaks -p CTCF.pwm -g hg38 -b > CTCF_motifs.bed``` command, but I get this error message:

>  Traceback (most recent call last):
  File "/Users/luca/anaconda3/envs/gimme/bin/gimme", line 513, in <module>
    args.func(args)
  File "/Users/luca/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/pwmscan.py", line 170, in pwmscan
    normalize=args.zscore,
  File "/Users/luca/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/pwmscan.py", line 113, in command_scan
    fa = as_fasta(inputfile, genome)
  File "/Users/luca/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/utils.py", line 613, in as_fasta
    genome.track2fasta(seqs, tmpfa.name) 
  File "/Users/luca/anaconda3/envs/gimme/lib/python3.6/site-packages/genomepy/functions.py", line 466, in track2fasta
    track_type = get_track_type(track)
  File "/Users/luca/anaconda3/envs/gimme/lib/python3.6/site-packages/genomepy/functions.py", line 231, in get_track_type
    if isinstance(track, []):
TypeError: isinstance() arg 2 must be a type or tuple of types

Do you have any suggestion to sort it out?

**To Reproduce:**
genome path is: ```.//.local/share/genomes/hg38/hg38.fa ```

this is the structure of my bed file:
> chr1:16100-16375
chr1:103922-104996
chr1:138811-139325
chr1:267382-268156
chr1:609167-610766
chr1:665825-666188
chr1:778686-779058
chr1:857890-858227
chr1:869737-870095
chr1:904592-904947

This is the pwm file I extracted from the motif_database:
>CTCF_known1 CTCF_1 CTCF_jaspar_MA0139.1
Y 0.095290 0.318729 0.083242 0.502738
D 0.182913 0.158817 0.453450 0.204819
R 0.307777 0.053669 0.491785 0.146769
C 0.061336 0.876232 0.023001 0.039430
C 0.008762 0.989047 0.000000 0.002191
A 0.814896 0.014239 0.071194 0.099671
S 0.043812 0.578313 0.365827 0.012048
Y 0.117325 0.474781 0.052632 0.355263
A 0.933114 0.012061 0.035088 0.019737
G 0.005488 0.000000 0.991218 0.003293
R 0.365532 0.003293 0.621295 0.009879
K 0.059276 0.013172 0.553238 0.374314
G 0.013187 0.000000 0.978022 0.008791
G 0.061538 0.008791 0.851648 0.078022
C 0.114411 0.806381 0.005501 0.073707
R 0.409241 0.014301 0.557756 0.018702
S 0.090308 0.530837 0.338106 0.040749
Y 0.128855 0.354626 0.080396 0.436123
V 0.442731 0.199339 0.292952 0.064978

I install the gimmemotifs package using conda with this command: ```conda create -n gimme python=3 gimmemotifs``` no more than a week ago. I saw there have been few probelm with the conda update.

```conda info``` gives:

>      active environment : gimme
    active env location : /Users/luca/anaconda3/envs/gimme
            shell level : 2
       user config file : /Users/luca/.condarc
 populated config files : /Users/luca/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/luca/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/luca/anaconda3/pkgs
                          /Users/luca/.conda/pkgs
       envs directories : /Users/luca/anaconda3/envs
                          /Users/luca/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

and ```conda list```:

> #
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
bcftools                  1.8                  h4da6232_3    bioconda
bedtools                  2.29.0               ha290c19_1    bioconda
boltons                   19.1.0                     py_0    conda-forge
bucketcache               0.12.1                   py36_1    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.6.16                py36_1    conda-forge
cffi                      1.12.3           py36hccf1714_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
cryptography              2.7              py36h212c5bf_0    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.4.0                      py_0    conda-forge
diskcache                 4.0.0                      py_0    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
feather-format            0.3.1                    py36_1    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
future                    0.17.1                py36_1000    conda-forge
gadem                     1.3.1                h470a237_1    bioconda
genomepy                  0.6.0                      py_0    bioconda
ghostscript               9.22              h0a44026_1001    conda-forge
gimmemotifs               0.13.1           py36h01d97ff_3    bioconda
homer                     4.10            pl526h770b8ee_0    bioconda
htslib                    1.7                           0    bioconda
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.8                   py36_1000    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
joblib                    0.14.0                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
kiwisolver                1.1.0            py36h770b8ee_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.0                         0    conda-forge
libcxxabi                 9.0.0                         0    conda-forge
libdeflate                1.3                  h01d97ff_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                hd44dcd8_1    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libuuid                   2.32.1            h1de35cc_1000    conda-forge
libxgboost                0.90                 h6de7cb9_2    conda-forge
libxml2                   2.9.9                h12c6b28_5    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
llvm-openmp               9.0.0                h40edb58_0    conda-forge
logbook                   1.4.3            py36h01d97ff_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py36h1de35cc_0    conda-forge
matplotlib                3.1.1                    py36_1    conda-forge
matplotlib-base           3.1.1            py36h3a684a6_1    conda-forge
meme                      4.12.0          py36pl526hd869df4_2    bioconda
mysql-connector-c         6.1.11            h42c63d9_1003    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
norns                     0.1.5                      py_0    bioconda
nose                      1.3.7                 py36_1002    conda-forge
numpy                     1.17.2           py36h6b0580a_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjdk                   11.0.1            h01d97ff_1017    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
pandas                    0.25.1           py36h86efe34_0    conda-forge
pathlib                   1.0.1                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
perl                      5.26.2            haec8ef5_1006    conda-forge
perl-algorithm-cluster    1.58            pl526h1de35cc_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-cgi                  4.40            pl526h470a237_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-html-parser          3.72            pl526h04f5b5a_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-template        2.97                    pl526_1    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-scalar-list-utils    1.52            pl526h01d97ff_0    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526h4c9d1cc_1002    conda-forge
perl-xml-sax              0.99                    pl526_1    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pillow                    6.2.0            py36hb6f49c9_0    conda-forge
pip                       19.2.3                   py36_0    conda-forge
py-xgboost                0.90             py36h6de7cb9_2    conda-forge
pybedtools                0.8.0            py36h5c9b4e4_1    bioconda
pycparser                 2.19                     py36_1    conda-forge
pyfaidx                   0.5.5.2                    py_1    bioconda
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pysam                     0.14.1           py36hae42fb6_1    bioconda
pysocks                   1.7.1                    py36_0    conda-forge
python                    3.6.7             h94afb7f_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-xxhash             1.3.0            py36h1de35cc_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pyyaml                    5.1.2            py36h01d97ff_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
represent                 1.6.0            py36h01d97ff_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
samtools                  1.7                           1    bioconda
scikit-learn              0.21.3           py36hd4ffd6c_0    conda-forge
scipy                     1.2.1            py36hbd7caa9_1    conda-forge
seaborn                   0.9.0                      py_1    conda-forge
setuptools                41.2.0                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sklearn-contrib-lightning 0.5.0                    py36_0    conda-forge
sqlite                    3.29.0               hb7d70f7_1    conda-forge
statsmodels               0.10.1           py36heacc8b8_0    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
tornado                   6.0.3            py36h01d97ff_0    conda-forge
tqdm                      4.36.1                     py_0    conda-forge
trawler                   2.0                     pl526_2    bioconda
ucsc-bedtogenepred        377                  he2eb843_0    bioconda
ucsc-bigbedtobed          366                  h1341992_0    bioconda
ucsc-genepredtobed        377                  he2eb843_2    bioconda
ucsc-genepredtogtf        377                  he2eb843_2    bioconda
ucsc-gff3togenepred       366                  h1341992_0    bioconda
ucsc-gtftogenepred        377                  he2eb843_2    bioconda
urllib3                   1.25.6                   py36_0    conda-forge
weeder                    2.0                  h04f5b5a_3    bioconda
wheel                     0.33.6                   py36_0    conda-forge
xdg                       3.0.2                         0    conda-forge
xgboost                   0.90             py36h6de7cb9_2    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xxmotif                   1.6                           0    bioconda
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zlib                      1.2.11            h01d97ff_1006    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge

I'm running it on MacOS Mojave version 10.14.6

Hope you can help me out.
Thanks in advance.

**Comment by simonvh** [comment]
Thanks for the detailed report, this really helps. It's a bug, that I will fix but that will take some time before it will be released. In the meantime, can you try the following.

Change your input file from:

```
chr1:16100-16375
chr1:103922-104996
chr1:138811-139325
```

to a tab-separated file like this:

```
chr1	16100	16375
chr1	103922	104996
chr1	138811	139325
```

The motif should be changed to a PFM format that looks like this, also tab-separated:

```
>CTCF_known1 CTCF_1 CTCF_jaspar_MA0139.1
0.095290	0.31872	0.083242	0.502738
0.182913	0.158817	0.453450	0.204819
0.307777	0.053669	0.491785	0.146769
0.061336	0.876232	0.023001	0.039430
0.008762	0.989047	0.000000	0.002191
0.814896	0.014239	0.071194	0.099671
...and so on...
```

If all goes well this should work.

**Comment by ls760** [comment]
Thanks for your answer. 
I created an environment with gimmemotifs==0.12.0. It worked fine.
Hope you'll sort the problem out.

**Comment by simonvh** [comment]
I've updated the conda build, should now be fixed.
