### ISSUE TITLE
Outdated dependency: scipy.misc

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/gimmemotifs#82]
**Describe the bug**
Scipy.misc is deprecated and replaced with scipy.special (as shown [here](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.factorial.html))

**To Reproduce**
1) install gimme motifs
2) initiate (for reference, I did this with `$gimme motif --help`)

**Expected behavior & Error logs**
![image](https://user-images.githubusercontent.com/48289046/67269937-ed5d0680-f4b7-11e9-998e-b4c8750f5e55.png)

**Installation information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation conda (manual from conda cloud)
 - Version 0.13.1 

**Additional context**
The error refers to gimme maelstrom (see image). Might be related to issue #81.

**Comment by siebrenf** [comment]
I see this was fixed in Develop. Leaving this Issue open, as new installations of gimme motifs will fail.

**Comment by simonvh** [comment]
Is this using the most recent gimmemotifs build from bioconda? That should install `scipy <1.3.0` to temporarily fix this issue until the current develop version is released.

**Comment by siebrenf** [comment]
Yes.

Command: conda install -c bioconda gimmemotifs
Installs v0.13.1 according to conda cloud.

The bioconda recipe does indeed show that dependency. However, when looking in my conda install log I see no reference to scipy anywhere... The issue might be that I did not use a clean conda environment.

**Comment by simonvh** [comment]
Does the same issue occur when installing gimmemotifs in a new env:

```
conda create -n gimme gimmemotifs
conda activate gimme
[...run...]
```

**Comment by siebrenf** [comment]
No.

In a new environment there were no issues.
After removing the config and creating the new environment there were no issues either.

**Comment by martynakgajos** [comment]
I had this problem in the new environment too.

**Comment by simonvh** [comment]
@martynakgajos can you post the the output of `conda info`  and `conda list`?
