### ISSUE TITLE
Hidden file dependency: genome.gaps.bed

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/gimmemotifs#85]
**description**
`gimme scan` requires a genome.gaps.bed to be present in the same folder as the genome. This requirement originates from genomepy > functions.py > gap_sizes.

_Placing this issue here as it also affects gimme motifs (feel free to close it if this makes no sense!). Will attempt to fix in Genomepy._

**additional info**
When installing a genome with Genomepy, there is apparently [a plugin](https://github.com/simonvh/genomepy/blob/master/genomepy/plugins/gaps.py) that can create this gaps.bed file. For other genomes (or without the plugin active), this is not done. And there seems to be no command to do this manually.

**solution**
An optimal solution would be if gap_sizes would check for existence of the file, and runs this plugin if it does not.

**Comment by siebrenf** [comment]
[fix underway](https://github.com/simonvh/genomepy/pull/48)

**Comment by simonvh** [comment]
@siebrenf  this is fixed with the new release of genomepy right?

**Comment by siebrenf** [comment]
Yes!
