### ISSUE TITLE
Find all occurrences of motifs in the genome

### ISSUE THREAD

**Issue by adomingues** [vanheeringen-lab/gimmemotifs#86]
Hi Simon,

the title of the issue is pretty self-explanatory: I am trying to find all the occurrences (positions) of a custom list of motifs (PWMs file) in the genome (Zebrafish if it matters). The overarching goal is to determine if a particular group of motifs is overrepresented in a (very large) region of the genome.  

For that I thought of using `gimme scan`. However after a couple of tries, and reading the docs, I am not sure if it (i) thi is the right tool for the job; or (ii) if I am using it correctly. For instance I divided the genome into large portions and ran:

```bash
gimme scan zv9.50kb_windows.bed --pwmfile Filtered_pmw.txt -g  genome.fasta -f 0.05 --bed > motifs_locations.bed
```
This finds the genomic location of some motifs, but not all the expected positions. I am assuming that this is because the genome is being used a background control against itself. 

Am I going about this the right way and do you have any suggestions?

**Comment by simonvh** [comment]
It should be possible, although I've never checked scanning a whole genome. You might run into memory issues, but only one way to find out!  The `-f 0.05`  will not work, as it will determine the FPR based on 50kb windows. Instead, you can use the `-c` argument, which sets a score threshold based on the maximum score per motif. This should probably be in the 0.9-1.0 range, where 1.0 is only perfect matches. One other parameter that you will have to change is `-n`. This is the maximum number of matches to report per sequence (window in your case), which by default is set to 1. This is kind of clunky, as you will need to set this to an arbitrarily large number (there is no option to just set to report "all" matches). In summary, the command would look something like this:

```
gimme scan zv9.50kb_windows.bed --pwmfile Filtered_pmw.txt -g  genome.fasta -c 0.95 -n 10000 --bed > motifs_locations.bed
```

Let me know how this works for you.

**Comment by adomingues** [comment]
Cheers Simon, that seems to have done the trick. 

> You might run into memory issues, but only one way to find out!

`gimme` is quite efficient :+1:  I ran the command in the login server of our cluster which has limited resources, and it took only a few minutes (about 2 - 3) for the full genome and it did not reach the mem limit. So all good. 

In the end it returned dozens of thousands up to hundreds of thousands for each motif, which is sort of expected.

Thanks a lot!
