### ISSUE TITLE
Bug on gimme background when narrowPeak file is used

### ISSUE THREAD

**Issue by irzhegalova** [vanheeringen-lab/gimmemotifs#87]
I wanted to compute background for my sequences, as I ran gimme background for it, but get suddenly smth about not enough sequences with GC between 0.9 and 0.95.
I must tell you, that I work with Dictiostelium genome, it is extremely GC-poor and such a high value is quite strange.

But then I got the idea that it is possible to be mismatched with AT-content. And I have found that in output file first columns of bedtools nuc is your input, but as I had narrowPeak file, it used all 4 columns and then put 5th column as AT-content. In line 202 of **gimmemotifs/background.py** you put 4 but in my file it should be 5.
To prevent future mistakes I ask you to deal with it narrowPeak files or with bedtools nuc header to use the right column to future work.

All the best!

Irina Zhegalova,
PhD student at Moscow State University

**Comment by simonvh** [comment]
Should be fixed in 0.14.0
