### ISSUE TITLE
Fasta parser class fails if the description contains '>' character

### ISSUE THREAD

**Issue by littleblackfish** [vanheeringen-lab/gimmemotifs#88]
Hello, 
I was experimenting with some custom segments from a genome, which I put into a fasta file using biopython. Biopython defaults to <Unknown id> <Unknown description> if I provide neither, so I have description lines that look like
`><unknown id> <unknown description>`
which breaks the fasta parser apparently, so I can't get past `divide_fa_file()` part unless I 'fix' my descriptions. 

Perhaps there is some value in using a standard library like SeqIO from biopython to avoid this kind of edge case problems?

**Comment by simonvh** [comment]
Yeah, if I would probably use biopython if I were to start this project now :). Might still be worth to do at this moment, however, for now I've implemented a quick fix.
