### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/gimmemotifs#95]
The bioconda recipe seems to only work with py3.6, which I think is caused by the requirement of `scipy < 1.3.0`. This requirement is in the development branch and the bioconda recipe.

Why is this? Gimmemotifs does not seem to use any of the backward incompatible changes:
https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html#scipy-1-3-0-release-notes

**Comment by simonvh** [comment]
See #82. This is fixed in develop, which is pretty much ready for release.

**Comment by Maarten-vd-Sande** [comment]
Ok great, thanks for the reply!
