### ISSUE TITLE
One or more setup errors occured  after installing gimme using  'conda create -n gimme python=3 gimmemotifs

### ISSUE THREAD

**Issue by Vickismemo** [vanheeringen-lab/gimmemotifs#98]
**Describe the bug**
>>
File "${mypath}/cli.py",line 179, in cli
).format(params["size"]),
KeyError:'size'
did it mean that the key 'size' do not  exist ?
>>

**To Reproduce**
when I ran `gimme motifs -h` ,the error was what I said 
>>
KeyError:'size'

**Expected behavior**

First of all,really thanks for your help,and how could I fix this error?

**Error logs**
If applicable, add error logs to help explain your problem.

There are several errors before the above one appears .The former problems have been solved while latter one is under handling.So ,I will list those steps and those errors.
First ,install this software using conda 
>>conda create -n gimme python=3 gimmemotifs
>>conda activate gimme
Error one:
from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
>>
So ,I installed the  'tqdm' using  command line `pip  install tqdm` ,and then systems display:
>>
Requirement already satisfied: tqdm in ./envs/gimme/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg (4.7.2)
>>
it was a file ,not a package.So ,I deleted that file ,and re-did `pip  install tqdm`.The systems display:
>>
Collecting tqdm
  Using cached https://files.pythonhosted.org/packages/7f/32/5144caf0478b1f26bd9d97f510a47336cf4ac0f96c6bc3b5af20d4173920/tqdm-4.40.2-py2.py3-none-any.whl
ERROR: gimmemotifs 0.14.0 requires configparser, which is not installed.
ERROR: gimmemotifs 0.14.0 requires xgboost>=0.71, which is not installed.
Installing collected packages: tqdm
Successfully installed tqdm-4.40.2
>>
then ,I install those packages using command line:
`pip  install  configparser`
`pip  install  xgboost`
>>
Collecting xgboost
  Downloading https://files.pythonhosted.org/packages/c1/24/5fe7237b2eca13ee0cfb100bec8c23f4e69ce9df852a64b0493d49dae4e0/xgboost-0.90-py2.py3-none-manylinux1_x86_64.whl (142.8MB)
     |████████████████████████████████| 142.8MB 231kB/s
Requirement already satisfied: scipy in ./Miniconda2/envs/gimme/lib/python3.6/site-packages (from xgboost) (1.3.2)
Requirement already satisfied: numpy in ./Miniconda2/envs/gimme/lib/python3.6/site-packages (from xgboost) (1.17.3)
Installing collected packages: xgboost
Successfully installed xgboost-0.90
>>
Then ,i ran `gimme motifs -h` ,the error was what I said 
>>
KeyError:'size'

**Installation information (please complete the following information):**
 - Linux: [e.g. OSX, Linux]
 - Installation :condacreate -n gimme python=3 gimmemotifs   [e.g. conda]
 - Version  0.14.0 [e.g. 0.13.0]

**Additional context**

**Comment by simonvh** [comment]
Thanks for your report. There seem to be two problems. The first is a dependency problem, I'll update the bioconda build to take of that in the future. 

For the second one, can you post the contents of your config file?  `~/.config/gimmemotifs/gimmemotifs.cfg`

**Comment by Vickismemo** [comment]
yes ,really thanks .
${mypath} equals to my directory, and is not a variable.
 The content 
#############################################
use_strand = Falsememotifs/gimmemotifs.cfg
abs_max = 1000
analysis = medium
enrichment = 1.5
width = 200
lwidth = 500
background = gc,random
cluster_threshold = 0.95
scan_cutoff = 0.9
available_tools = MDmodule,MEME,MEMEW,Weeder,GADEM,MotifSampler,Trawler,Improbizer,BioProspector,Posmo,ChIPMunk,AMD,HMS,Homer
tools = MDmodule,MEME,Weeder,MotifSampler,trawler,Improbizer,BioProspector,Posmo,ChIPMunk,AMD,Homer
pvalue = 0.001
max_time = -1
ncpus = 12
motif_db = gimme.vertebrate.v5.0.pfm
use_cache = False

[AMD]
bin = AMD.bin
dir = included_tools/

[MEME]
bin =${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin/meme
dir = ${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin

[MEMEW]
bin = ${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin/meme
dir =${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin

[MDmodule]
bin = MDmodule
dir = included_tools/

[Improbizer]
bin = ameme
dir = included_tools/

[MotifSampler]
bin = MotifSampler
dir = included_tools/

[GADEM]
bin = ${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin/gadem
dir = ${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin

[Trawler]
bin = ${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin/trawler
dir = ${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin

[Weeder]
bin = ${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin/weeder2
dir = ${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin

[BioProspector]
bin = BioProspector
dir = included_tools/

[ChIPMunk]
bin = ChIPMunk.sh
dir = included_tools/ChIPMunk

[Homer]
bin =${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin/homer2
dir = ${mypath}/Miniconda2/envs/gimmemotifs_v0.14.0/bin

[XXmotif]
bin = XXMotif
dir = included_tools/

[Posmo]
bin = posmo
dir = included_tools/

[HMS]
bin = hms
dir = included_tools/HMS

really thanks again.

**Comment by simonvh** [comment]
Can you change the following line:

```
width = 200
```

to:

```
size = 200
```

and try again?

**Comment by Vickismemo** [comment]
yes ，when I change the "width" to "size",it works .
Really thanks for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Simon van Heeringen"<notifications@github.com&gt;; 
发送时间: 2019年12月17日(星期二) 下午3:08
收件人: "vanheeringen-lab/gimmemotifs"<gimmemotifs@noreply.github.com&gt;; 
抄送: "杨巍"<289903262@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vanheeringen-lab/gimmemotifs] One or more setup errors occured  after installing gimme using  &#39;conda create -n gimme python=3 gimmemotifs (#98)




Can you change the following line:
 width = 200  
to:
 size = 200  
and try again?

**Comment by simonvh** [comment]
Great! 

If you have time, can you post the output of the following command:

```
conda list | grep tqdm
```

I cannot reproduce the `tqdm` error, it seems to be related to a very specific conda build of that package.

**Comment by Vickismemo** [comment]
yes,my preasure,sorry for late
the content:
$conda list |grep tqdm
tqdm&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4.40.2&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;py_0&nbsp; &nbsp; conda-forge





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Simon van Heeringen"<notifications@github.com&gt;; 
发送时间: 2019年12月19日(星期四) 下午4:08
收件人: "vanheeringen-lab/gimmemotifs"<gimmemotifs@noreply.github.com&gt;; 
抄送: "杨巍"<289903262@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vanheeringen-lab/gimmemotifs] One or more setup errors occured  after installing gimme using  &#39;conda create -n gimme python=3 gimmemotifs (#98)




Great!
 
If you have time, can you post the output of the following command:
 conda list | grep tqdm  
I cannot reproduce the tqdm error, it seems to be related to a very specific conda build of that package.

**Comment by Rmulet** [comment]
I also encountered the `tqdm` error. The version of that module I am using is 4.7.2:

> tqdm                      4.7.2                    py36_0    bioconda

**Comment by simonvh** [comment]
Thanks, that helps! Apparently, an older version of `tqdm` gets pulled in. I have tracked down the minimum version and I'll update the build.
