### ISSUE TITLE
Gimmemotifs not updating to 0.14 with conda

### ISSUE THREAD

**Issue by Rmulet** [vanheeringen-lab/gimmemotifs#99]
**Describe the bug**
I tried to update gimmemotifs to its latest version (0.14.0) with `conda update gimmemotifs`, but it reports that the latest version is already installed and does not proceed further. This is not true according to `conda info`: version 0.13.1 is installed, not 0.14.0.

Interestingly, `conda search gimmemotifs` found that 0.14.0 is available on the bioconda channel. If I force installation of said version with `conda install gimmemotifs=0.14.0`, it is installed successfully. However, as reported in another post, the program won't run because of dependency issues with `tqdm`.

**To Reproduce**
conda update gimmemotifs

**Expected behavior**
Conda should install the latest available version of gimmemotifs, but instead it get stuck at version 0.13.1.

**Installation information (please complete the following information):**
 - OS: Linux
 - Installation: conda
 - Version: 0.13.1

**Comment by simonvh** [comment]
I'll fix the conda issue related to the `tqdm` dependency, however, the update issue is new to me I'll look into it!

**Comment by simonvh** [comment]
If you have time, can you post the output of the following command:

```
conda list | grep tqdm
```

I cannot reproduce the `tqdm` error, it seems to be related to a very specific conda build of that package.

**Comment by simonvh** [comment]
I cannot reproduce this update bug. Did you have `gimmemotifs` installed in a separate environment or in your `base` environment? Maybe there is a dependency issue that clashes with other packages?

**Comment by Rmulet** [comment]
Apologies for the delay. I was on a long vacation and I did not have time to check this out.

I have `gimmemotifs` installed in my base environment, so that could be indeed the reason. However, `conda` does complain about dependency issues; it simply reports that the latest version is already installed. 

I also have a separate `conda` environment with the latest version available, but there I encountered the `tqdm` issue that I already reported in the other thread.

**Comment by simonvh** [comment]
> I have `gimmemotifs` installed in my base environment, so that could be indeed the reason. However, `conda` does complain about dependency issues; it simply reports that the latest version is already installed.

I do think this could be the issue. From the [`conda update`](https://docs.conda.io/projects/conda/en/latest/commands/update.html) documentation (emphasis mine):

>This command accepts a list of package names and updates them to the latest versions **that are compatible** with all other packages in the environment.

My hunch is that it will not give any error or warnings but just updates `gimmemotifs` to the latest version that does not conflict with anything else.
That being said, as I cannot reproduce the error, it remains a hunch...
